/*
 * Série 3 — diferenciação agressiva.
 *
 * As 69 receitas do banco cabem quase todas em três moldes: packshot com texto ao
 * lado, grade de módulos e modelo em locação. Esta série existe para atacar isso.
 * Cada direção aqui parte de um recurso fotográfico que NENHUMA referência do banco
 * usa hoje — escala, repetição, movimento, sombra, cor de fundo, altura, corte.
 *
 * As quatro últimas são correções: a direção estava certa, a receita é que não
 * declarava a cor e o modelo foi para o vermelho de liquidação (erro nº 3 da
 * diretriz 23). Agora a cor está escrita.
 */
export const serie3 = [
  /* ---------- 1. escala: o produto não cabe no quadro ---------- */
  {
    id: 'NOVA-37',
    nome: 'Macro que estoura as bordas com oferta minúscula',
    caminho: 'produto único · até X% · estética · sem pessoa · um produto',
    mode: 'single', mech: 'percentual', argumento: 'estetica',
    alvo: 'Tênis de couro branco', categoria: 'calçados',
    variantes: ['branco'],
    detalhes: 'couro liso sem logo, cadarço plano, solado de borracha branca',
    publico: 'Homem de 25 a 45 anos que compra tênis pelo desenho.',
    oferta: 'ATÉ 70% DE DESCONTO',
    people: 'sem-pessoa', slots: 1,
    receita: [
      'O que define esta direção: o produto é fotografado tão perto que não cabe no quadro — ele entra por uma borda e sai pela outra, cortado dos dois lados. A textura do material é o assunto, e o texto é minúsculo ao lado.',
      'Fundo do mesmo material do produto continuando atrás dele, sem cenário, superfície ou horizonte visível.',
      'O produto atravessa o quadro na diagonal, cortado nas duas pontas. Costura, textura, cadarço e acabamento aparecem em detalhe absoluto, com foco fechadíssimo e profundidade curta.',
      'Luz rasante de um lado só, criando relevo forte na textura e sombra funda no lado oposto.',
      'Num canto, em corpo pequeno e discreto, empilhados: a marca e a oferta em duas linhas. O texto é o menor elemento da peça e não disputa com a foto.',
      'Nenhuma cor gráfica: o texto é claro ou escuro conforme o fundo, e toda a cor vem do produto.',
      'Esta peça não tem pessoa, packshot inteiro, selo, moldura, benefício ou CTA. Nada de mostrar o produto por completo.',
    ],
  },

  /* ---------- 2. repetição serial: o produto vira padrão ---------- */
  {
    id: 'NOVA-38B',
    nome: 'Padrão serial denso com uma unidade fora de linha',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · muitas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Camiseta básica masculina de algodão', categoria: 'vestuário masculino',
    variantes: ['branca', 'preta', 'cinza', 'azul-marinho', 'verde-oliva'],
    detalhes: 'gola careca, manga curta, malha lisa sem estampa e sem logo',
    publico: 'Homem de 20 a 40 anos que compra camiseta básica em quantidade.',
    oferta: 'COMPRE 4, LEVE 6',
    people: 'sem-pessoa', slots: 5, fillsWithVariants: true, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: a mesma unidade se repete em fileiras apertadas até virar padrão, cobrindo o quadro inteiro de borda a borda. Uma única unidade sai da linha e é o que segura o olho.',
      'Não existe fundo visível: as unidades dobradas preenchem tudo, encostadas, em fileiras regulares, com as bordas cortadas pelo limite do quadro.',
      'Todas as unidades estão no mesmo ângulo, no mesmo tamanho e na mesma luz plana e frontal, alternando as cores confirmadas em ritmo regular.',
      'Uma única unidade, fora do centro, está girada e levemente erguida, projetando sombra sobre as vizinhas. É a única quebra do padrão.',
      'A oferta e a marca ficam num canto livre do quadro, em corpo pequeno e escuro, aplicadas por cima da fotografia.',
      'Nenhuma peça tem estampa, letra, número ou desenho impresso: as unidades são lisas, e o texto da peça nunca vira estampa do produto.',
      'A repetição é o argumento: dá para ver que são muitas, sem precisar contar.',
      'Esta peça não tem pessoa, cenário, faixa, selo, moldura, benefício ou CTA.',
      'Com menos cores confirmadas, o padrão repete as cores reais com mais frequência; nenhuma cor nova é inventada.',
    ],
  },

  /* ---------- 3. movimento congelado ---------- */
  {
    id: 'NOVA-39',
    nome: 'Unidades em queda congelada no ar',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · três unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Boné de sarja com aba curva', categoria: 'acessórios',
    variantes: ['preto', 'bege', 'verde-oliva'],
    detalhes: 'sarja lisa sem bordado, aba curva, fecho traseiro de metal',
    publico: 'Adulto de 18 a 35 anos que compra boné como acessório de estilo.',
    oferta: 'COMPRE 2, LEVE 3',
    people: 'sem-pessoa', slots: 3, fillsWithVariants: true,
    receita: [
      'O que define esta direção: as unidades estão no ar, congeladas no meio de uma queda, em alturas e rotações diferentes. Nada toca o chão e não existe apoio, mesa, plinto ou fio à vista.',
      'Fundo de estúdio claro, liso e contínuo, com sombras suaves e desalinhadas no piso, muito abaixo dos produtos, provando a altura.',
      'As unidades ocupam o terço central do quadro, cada uma numa altura e num giro diferente, todas nítidas e sem borrão de movimento.',
      'A de cima aparece um pouco menor e mais distante; a de baixo, maior e mais perto. A diferença de tamanho conta a queda.',
      'No alto, alinhados à esquerda: a marca pequena e a oferta em duas linhas de caixa alta pesada e escura. O texto ocupa a área vazia acima da queda.',
      'Esta peça não tem pessoa, mão, cenário, faixa, selo, moldura ou CTA. Nada de suporte visível segurando o produto.',
      'Com menos cores confirmadas, caem menos unidades e o espaço vazio aumenta.',
    ],
  },

  /* ---------- 4. a sombra é o elemento gráfico ---------- */
  {
    id: 'NOVA-40',
    nome: 'Sombra dura de persiana cortando o produto',
    caminho: 'produto único · até X% · estética · sem pessoa · um produto · peça sem texto',
    mode: 'single', mech: 'percentual', argumento: 'estetica',
    alvo: 'Óculos de sol com armação de acetato', categoria: 'acessórios',
    variantes: ['preto'],
    detalhes: 'armação de acetato grossa sem logo, lente escura, hastes retas',
    publico: 'Adulto de 20 a 40 anos que compra óculos de sol pelo desenho.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'sem-pessoa', slots: 1, silent: true,
    receita: [
      'O que define esta direção: uma sombra dura de persiana atravessa o quadro em faixas paralelas e passa por cima do produto. A sombra é o elemento gráfico da peça, e não existe nenhum texto.',
      'Superfície e parede em concreto claro e liso, contínuos, sob sol forte e direto.',
      'Faixas de sombra retas e bem marcadas cruzam o quadro na diagonal, com bordas nítidas e espaçamento regular, cobrindo parte do produto e parte do fundo.',
      'O produto fica no centro, em três quartos, com pelo menos uma faixa de luz cheia atravessando sua parte principal — a silhueta inteira continua legível mesmo com as faixas por cima.',
      'O contraste entre luz e sombra é alto, sem meio-tom.',
      'Esta peça não tem texto, marca, pessoa, objeto de cena, selo, moldura ou efeito gráfico aplicado. A única geometria é a sombra real.',
    ],
  },

  /* ---------- 5. fundo de cor chapada (o banco é todo neutro) ---------- */
  {
    id: 'NOVA-41',
    nome: 'Produto sobre cor chapada saturada',
    caminho: 'produto único · até X% · estética · sem pessoa · duas cores',
    mode: 'single', mech: 'percentual', argumento: 'estetica',
    alvo: 'Garrafa térmica de aço', categoria: 'utilidades',
    variantes: ['preta', 'off-white'],
    detalhes: 'corpo cilíndrico de aço fosco sem logo, tampa rosqueável',
    publico: 'Adulto de 20 a 45 anos que leva bebida consigo na rotina.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'sem-pessoa', slots: 2, fillsWithVariants: true,
    receita: [
      'O que define esta direção: o quadro inteiro é uma única cor chapada e saturada, e o produto flutua sobre ela. É a peça mais colorida do banco, e a cor é do fundo, nunca do texto.',
      'Fundo de uma só cor viva, forte e uniforme — sem gradiente, textura, cenário ou horizonte. A cor é escolhida para contrastar com o produto: escura se o produto for claro, clara e saturada se o produto for escuro.',
      'As unidades ficam em pé no centro, lado a lado e levemente desalinhadas em altura, com sombra de contato curta e da mesma cor do fundo, um tom mais escura.',
      'No alto, centralizada, a oferta em caixa alta pesada, em branco ou preto puro conforme a leitura sobre a cor. A marca pequena fica na base, centralizada, na mesma cor do texto.',
      'Só existem duas cores na peça inteira: a do fundo e a do texto. Todo o resto vem dos produtos.',
      'Esta peça não tem pessoa, cenário, faixa, selo, moldura, benefício escrito ou CTA.',
      'Com uma cor confirmada, fica uma unidade só, centralizada, e o fundo ganha mais respiro.',
    ],
  },

  /* ---------- 6. altura: torre vertical ---------- */
  {
    id: 'NOVA-42',
    nome: 'Torre alta de unidades cortada pelo topo',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · muitas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Toalha de banho de algodão', categoria: 'casa',
    variantes: ['branca', 'cinza', 'areia', 'verde-sálvia'],
    detalhes: 'algodão felpudo liso, barra lisa sem bordado',
    publico: 'Adulto de 25 a 55 anos que troca o jogo de toalhas inteiro.',
    oferta: 'COMPRE 3, LEVE 5',
    people: 'sem-pessoa', slots: 4, fillsWithVariants: true, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: uma torre de unidades dobradas sobe do pé do quadro e sai cortada pelo topo. Não dá para ver onde termina, e é isso que anuncia a quantidade.',
      'Fundo claro, liso e contínuo, com luz lateral suave e sombra longa da torre projetada para o lado.',
      'A torre é estreita e muito alta, ligeiramente fora do centro, com as unidades empilhadas em alinhamento solto, uma levemente deslocada da outra. As cores confirmadas se alternam subindo.',
      'A câmera está na altura da base, ligeiramente abaixo, olhando para cima — a torre afina no topo e reforça a altura.',
      'Na faixa vertical livre ao lado da torre, alinhados à esquerda e na base: a marca pequena e a oferta em duas linhas de caixa alta pesada.',
      'Esta peça não tem pessoa, mão, prateleira, cenário, faixa, selo ou CTA.',
      'Com menos cores confirmadas, a torre alterna as cores reais; a altura nunca diminui.',
    ],
  },

  /* ---------- 7. duas escalas do mesmo produto ---------- */
  {
    id: 'NOVA-43',
    nome: 'Produto gigante atrás, produto real na frente',
    caminho: 'produto único · até X% · função · sem pessoa · um produto',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Aparador de pelos elétrico', categoria: 'cuidados pessoais',
    variantes: ['grafite'],
    detalhes: 'corpo emborrachado, lâmina de aço destacável, botão único',
    beneficios: ['Lâmina que não puxa', 'Bateria para 90 minutos', 'À prova de água'],
    publico: 'Homem de 20 a 45 anos que se apara em casa.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'sem-pessoa', slots: 1,
    receita: [
      'O que define esta direção: o mesmo produto aparece duas vezes no mesmo quadro, em escalas muito diferentes — um close gigante e desfocado ocupando o fundo inteiro, e a unidade completa e nítida na frente. A peça mostra o detalhe e o produto de uma vez só.',
      'Não existe fundo de estúdio: o fundo é o próprio produto, em macro, muito desfocado, mostrando só textura e cor.',
      'Na frente, a unidade inteira aparece em três quartos, pequena em relação ao fundo, absolutamente nítida, com sombra de contato curta.',
      'A parte do produto que está gigante ao fundo é justamente a que o benefício principal descreve.',
      'Na área mais limpa do fundo desfocado, alinhados à esquerda: a marca pequena, os benefícios em linhas curtas separadas por filetes finos, e a oferta na base com o número em corpo grande.',
      'O texto é claro sobre o fundo escuro, ou escuro sobre o fundo claro — nunca uma terceira cor.',
      'Esta peça não tem pessoa, ícone, cartão, selo, moldura, estrela de avaliação ou CTA.',
    ],
  },

  /* ---------- 8. corte diagonal ---------- */
  {
    id: 'NOVA-44',
    nome: 'Split diagonal entre o produto e a oferta',
    caminho: 'produto único · compre X leve Y · função · sem pessoa · duas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Squeeze esportivo com bico de sucção', categoria: 'esportes',
    variantes: ['preto'],
    detalhes: 'corpo flexível sem logo, bico de sucção, alça de dedo',
    beneficios: ['Não vaza', 'Bebe sem parar de correr', 'Lava na máquina'],
    publico: 'Adulto de 20 a 45 anos que corre e treina.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'sem-pessoa', slots: 2, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: uma linha diagonal corta o quadro de canto a canto e divide a peça em dois territórios — de um lado a fotografia, do outro um campo de cor sólida com a oferta. O corte é inclinado, nunca vertical nem horizontal.',
      'Do lado da fotografia, as duas unidades aparecem deitadas e cruzadas sobre superfície escura e fosca, com luz lateral dura e sombra curta.',
      'Do outro lado da diagonal, um campo de cor sólida e escura, sem textura, sem foto e sem degradê.',
      'Sobre o campo sólido, acompanhando a inclinação da diagonal: a oferta em caixa alta pesada e clara em duas linhas, os benefícios em linhas curtas abaixo, e a marca pequena na base.',
      'Nenhuma unidade cruza a diagonal: a foto termina exatamente onde o campo começa.',
      'Só existem duas cores gráficas: o escuro do campo e o claro do texto.',
      'Esta peça não tem pessoa, ícone, cartão, selo, moldura ou CTA.',
    ],
  },

  /* ---------- correções: a direção estava certa, faltava declarar a cor ---------- */
  {
    id: 'NOVA-29B',
    nome: 'Mão com o produto e tópicos em linha fina',
    caminho: 'produto único · até X% · função · corpo sem rosto · duas cores',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Escova de dentes elétrica recarregável', categoria: 'higiene pessoal',
    variantes: ['branca', 'preta'],
    detalhes: 'cabo liso, um botão frontal, base de carregamento redonda',
    beneficios: ['Remove mais placa que a escova manual', 'Carga dura semanas', 'Timer de dois minutos'],
    publico: 'Adulto de 25 a 50 anos que quer trocar a escova manual pela elétrica.',
    oferta: 'ATÉ 50% DE DESCONTO',
    people: 'corpo-suporte', slots: 2, fillsWithVariants: true,
    receita: [
      'O que define esta direção: a mão mostra o produto de perto, a segunda cor fica em pé na base, e o argumento vem em três tópicos com ícone de linha fina.',
      'Fundo de banheiro claro, azulejo branco liso e desfocado.',
      'A mão, só até o pulso, segura uma unidade em pé. A outra cor fica em pé na base, ao lado e um pouco atrás.',
      'Do outro lado do quadro, empilhados e alinhados à esquerda: a marca pequena no alto; três tópicos curtos, cada um com um ícone de linha fina solto, sem círculo e sem fundo; e a oferta na base, com o número em corpo grande.',
      'Todo o texto e todo o ícone são escuros sobre o fundo claro. A peça não tem nenhuma cor de acento, nem no número, nem em selo, nem em faixa: a única cor do quadro vem do produto.',
      'Esta peça não tem selo, cartão, estrela de avaliação ou CTA.',
      'Com uma cor só, a unidade da base some e a mão fica sozinha.',
    ],
  },
  {
    id: 'NOVA-30B',
    nome: 'Mão na bancada com as cores ao lado',
    caminho: 'produto único · até X% · função · corpo sem rosto · três cores',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Mini liquidificador portátil recarregável', categoria: 'eletroportáteis',
    variantes: ['branco', 'verde-menta', 'rosa-claro'],
    detalhes: 'copo transparente com tampa, base com um botão, carregamento USB',
    beneficios: ['Vitamina pronta em 30 segundos', 'Leva na bolsa', 'Carrega no USB'],
    publico: 'Adulto de 25 a 45 anos que prepara vitamina e shake em casa, sem tempo.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'corpo-suporte', slots: 3, fillsWithVariants: true,
    receita: [
      'O que define esta direção: uma mão ergue o produto cheio de vitamina numa cozinha real, e as outras cores estão em pé na bancada, na mesma luz. Uso e variedade na mesma foto.',
      'Cozinha clara, bancada de pedra clara e parede lisa clara ao fundo, com luz de janela.',
      'Só a mão e o antebraço aparecem, entrando pela borda com uma unidade cheia. As outras ficam em pé na bancada, ao lado, inteiras.',
      'Na parede livre, alinhados à esquerda: a marca pequena, uma headline de duas linhas com o benefício principal em caixa alta pesada e a oferta em uma linha.',
      'Todo o texto é escuro sobre a parede clara. A peça não tem selo, tarja, cartão nem nenhuma cor de acento: a única cor do quadro vem dos produtos e do conteúdo do copo.',
      'Esta peça não tem lista de tópicos, ícone ou CTA.',
      'Com menos cores confirmadas, a bancada fica com menos unidades.',
    ],
  },
  {
    id: 'NOVA-33B',
    nome: 'Os dois joelhos, uma unidade em cada',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · duas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Joelheira de compressão', categoria: 'saúde e bem-estar',
    variantes: ['preta'],
    detalhes: 'malha de compressão lisa, abertura na patela, sem logo',
    beneficios: ['Alivia a dor ao caminhar', 'Estabiliza o joelho', 'Não escorrega'],
    publico: 'Adulto de 35 a 60 anos que sente dor no joelho ao caminhar ou subir escada.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'corpo-suporte', slots: 2, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: o produto vem em par porque o corpo tem dois joelhos. As duas pernas aparecem lado a lado, cada joelho com uma unidade.',
      'Fundo de estúdio claro e liso.',
      'As pernas aparecem de frente, lado a lado, enquadradas do meio da coxa até o meio da canela. A bermuda é lisa, neutra e escura.',
      'Numa faixa lateral clara, alinhados à esquerda: a marca pequena, os três benefícios em linhas curtas separadas por filetes finos e a oferta na base, em caixa alta pesada.',
      'Todo o texto, todo o filete e todo o ícone são escuros sobre a faixa clara. A peça não tem tarja colorida, selo colorido nem número em cor: a única cor do quadro é a pele e o preto do produto.',
      'Esta peça não tem cartão, moldura, estrela de avaliação ou CTA.',
    ],
  },
  {
    id: 'NOVA-36B',
    nome: 'Produto em uso visto de costas',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · um produto',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Fone de condução óssea', categoria: 'eletrônicos',
    variantes: ['preto'],
    detalhes: 'arco de titânio que passa atrás da nuca, apoio sobre a maçã do rosto, sem cabo',
    beneficios: ['Ouve música e o ambiente ao mesmo tempo'],
    publico: 'Homem de 20 a 45 anos que corre ao ar livre.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'corpo-suporte', slots: 1,
    receita: [
      'O que define esta direção: o produto em uso visto de costas, durante uma corrida real, com uma headline de benefício sobre o céu claro.',
      'Parque aberto com céu claro e liso ocupando a parte de cima do quadro; o resto do fundo levemente desfocado.',
      'A pessoa é vista de costas e de perto: nuca, orelhas e ombros, com o arco do fone passando atrás da nuca. Camiseta lisa em tom neutro.',
      'Sobre o céu, alinhados à esquerda: a marca pequena, uma headline de duas linhas com o benefício em caixa alta pesada e a oferta em uma linha abaixo.',
      'Todo o texto é escuro sobre o céu claro. A peça não tem tarja, caixa, selo nem cor de acento: a única cor do quadro vem da própria cena.',
      'Esta peça não tem lista de tópicos, ícone, cartão ou CTA.',
    ],
  },
];
