/*
 * Segunda série de direções novas, escrita para rodar em lote.
 *
 * Cada uma cai numa célula que o mapa de lacunas mostrava vazia ou rala depois que
 * as sete primeiras aprovadas entraram: caminho do aluno × presença humana ×
 * quantidade. Dentro de uma mesma célula, duas direções nunca repetem a família.
 *
 * `silent: true` troca o bloco de oferta pela regra da peça sem texto — criativo sem
 * texto também é referência e entra no lote como qualquer outro.
 */
export const serie2 = [
  /* ---------- produto único · até X% · estética ---------- */
  {
    id: 'NOVA-09',
    caminho: 'produto único · até X% · estética · corpo sem rosto · duas cores',
    nome: 'Duas mãos, a mesma bolsa em duas cores',
    people: 'corpo-suporte',
    publico: 'Mulher de 25 a 45 anos que compra bolsa pelo desenho e pela cor.',
    produto: 'duas bolsas de mão do mesmo modelo, uma off-white e uma caramelo, cada uma segurada por uma mão',
    oferta: 'ATÉ 60% DE DESCONTO',
    composicao: [
      'O que define esta direção: duas mãos entram por lados opostos do quadro, cada uma segurando a mesma bolsa numa cor diferente. O gesto repetido mostra que existem opções sem virar mostruário.',
      'Fundo de parede lisa clara e quente, contínuo, com luz lateral suave e sombra curta das bolsas na parede.',
      'Cada mão aparece só até o pulso, entrando pela borda. As duas bolsas ficam na mesma altura, lado a lado, com folga entre elas, e são os dois elementos mais nítidos e mais iluminados.',
      'No alto, centralizado: a marca pequena e espaçada, e abaixo a oferta em uma linha de caixa alta pesada.',
      'Nenhuma cor gráfica além do texto escuro. Toda a cor vem das bolsas.',
      'Esta peça não tem selo, cartão, etiqueta, benefício escrito nem CTA.',
    ],
  },
  {
    id: 'NOVA-10',
    caminho: 'produto único · até X% · estética · corpo sem rosto · quatro cores',
    nome: 'Close sem rosto abraçando a pilha das outras cores',
    people: 'corpo-suporte',
    publico: 'Mulher de 25 a 45 anos que compra tricô pela cor e pelo caimento.',
    produto: 'um cardigã de tricô do mesmo modelo em quatro cores — um vestido em verde-oliva por uma mulher e três dobrados em pilha nos braços dela, em creme, caramelo e cinza',
    oferta: 'ATÉ 70% DE DESCONTO',
    composicao: [
      'O que define esta direção: uma pessoa fotografada de perto, do maxilar para baixo, veste uma cor e segura contra o corpo a pilha dobrada das outras três. Caimento e variedade de cores cabem no mesmo enquadramento fechado, sem cenário.',
      'Fundo de parede lisa clara e quente, contínuo, com luz natural de janela vinda de um lado.',
      'A pessoa fica de frente, enquadrada do maxilar até o quadril, em close. O rosto não aparece. A calça é lisa, neutra, em tom escuro e apagado, claramente secundária.',
      'Os dois braços seguram a pilha dobrada na altura da cintura, sem cobrir a frente do cardigã vestido. Cada cor da pilha aparece inteira na borda dobrada. O cardigã vestido é o maior elemento do quadro.',
      'Na faixa livre de parede ao lado da pessoa, alinhado à esquerda: a marca pequena, e abaixo a oferta em duas linhas de caixa alta pesada.',
      'Esta peça não tem selo, cartão, moldura, joia, benefício escrito nem CTA.',
    ],
  },
  {
    id: 'NOVA-11',
    caminho: 'produto único · até X% · estética · sem pessoa · um produto · peça sem texto',
    nome: 'Produto sozinho em luz de fim de tarde, sem texto',
    people: 'sem-pessoa',
    silent: true,
    publico: 'Homem de 25 a 45 anos que compra tênis pelo desenho.',
    produto: 'um tênis de couro branco, liso e sem marca aparente',
    composicao: [
      'O que define esta direção: o produto sozinho, iluminado por uma faixa de sol de fim de tarde que atravessa a cena. A luz é o argumento; não há texto nenhum.',
      'Superfície de concreto claro e liso, com parede do mesmo material ao fundo. Uma faixa de luz quente e recortada cruza a parede e a superfície; o resto da cena fica em sombra suave.',
      'O tênis fica dentro da faixa de luz, em perfil de três quartos, com sombra longa e nítida projetada para trás.',
      'O produto é o ponto mais claro e mais nítido do quadro.',
      'Esta peça não tem pessoa, texto, selo, moldura nem objeto de cena.',
    ],
  },

  /* ---------- produto único · compre X leve Y · estética (vestuário primeiro) ---------- */
  {
    id: 'NOVA-12',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · quatro cores',
    nome: 'Grade de quatro closes sem rosto, uma cor por módulo',
    people: 'corpo-suporte',
    publico: 'Homem de 20 a 40 anos que compra camiseta básica em quantidade.',
    produto: 'quatro camisetas lisas masculinas do mesmo modelo, em branco, preto, azul-marinho e verde-oliva, cada uma vestida por um homem',
    oferta: 'COMPRE 3, LEVE 4',
    composicao: [
      'O que define esta direção: o quadro é uma grade de quatro módulos iguais, dois por dois, e em cada módulo uma pessoa fotografada de perto, do maxilar para baixo, veste a mesma camiseta numa cor diferente. A repetição do mesmo produto é o que anuncia o “leve mais”.',
      'Os quatro módulos têm o mesmo fundo de estúdio claro e liso, a mesma luz e o mesmo enquadramento, separados por um filete fino claro.',
      'Em cada módulo, uma pessoa de frente, enquadrada do maxilar até o quadril, em close. O rosto não aparece. As calças são lisas, neutras, iguais nos quatro módulos e claramente secundárias.',
      'Em cada módulo, a camiseta é o maior bloco de cor. Braços relaxados, sem cobrir a frente da camiseta.',
      'Na base, uma faixa sólida escura de ponta a ponta com a oferta em caixa alta pesada e clara — o maior texto da peça — e a marca pequena ao lado.',
      'Esta peça não tem selo, cartão, moldura, benefício escrito, acessório em destaque nem CTA.',
    ],
  },
  {
    id: 'NOVA-13',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · três cores',
    nome: 'Uma mão segurando três cabides',
    people: 'corpo-suporte',
    publico: 'Homem de 25 a 45 anos que compra camisa polo em mais de uma cor.',
    produto: 'três camisas polo do mesmo modelo, em branco, azul-marinho e verde-escuro, em três cabides de madeira seguros por uma única mão',
    oferta: 'COMPRE 2, LEVE 3',
    composicao: [
      'O que define esta direção: uma mão ergue três cabides de uma vez, com as três cores levemente abertas em leque. É o gesto de quem já decidiu levar as três.',
      'Fundo de parede lisa clara e quente, contínuo, sem cenário.',
      'Só a mão e o pulso aparecem, entrando pelo alto do quadro. As três peças pendem em leque, a da frente inteira e as outras duas aparecendo pela lateral, cada cor nitidamente separada.',
      'As peças ocupam o centro do quadro e são o elemento mais iluminado.',
      'Embaixo, centralizado: a oferta em uma linha de caixa alta pesada e, logo abaixo, a marca pequena e espaçada.',
      'Esta peça não tem selo, cartão, etiqueta, benefício escrito nem CTA.',
    ],
  },
  {
    id: 'NOVA-14',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · um produto',
    nome: 'Close vestido com a oferta gigante atrás',
    people: 'corpo-suporte',
    publico: 'Homem de 20 a 40 anos que compra camiseta pesada de algodão.',
    produto: 'uma camiseta lisa de algodão pesado, cor areia, vestida por um homem',
    oferta: 'COMPRE 2, LEVE 3',
    composicao: [
      'O que define esta direção: um único produto vestido e uma oferta tipográfica enorme atrás dele. A oferta de quantidade vive só no texto, e a foto mostra caimento.',
      'Fundo de estúdio escuro, liso e contínuo, com luz lateral recortando o corpo.',
      'A pessoa fica de frente, no centro, enquadrada do maxilar até o quadril, em close. O rosto não aparece. A calça é lisa, escura e apagada, claramente secundária. A camiseta é o ponto mais claro do quadro.',
      'Por trás da pessoa, atravessando a largura do quadro, a oferta em caixa alta pesada e clara, em duas linhas — a pessoa fica na frente de parte das letras sem impedir a leitura.',
      'A marca pequena e clara fica no pé do quadro, centralizada.',
      'Esta peça não tem selo, cartão, benefício escrito nem CTA.',
    ],
  },
  {
    id: 'NOVA-15',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · duas unidades',
    nome: 'Duas unidades dobradas com um sinal de mais',
    people: 'sem-pessoa',
    publico: 'Adulto de 25 a 45 anos que compra calça jeans e já leva a segunda.',
    produto: 'duas calças jeans do mesmo modelo, uma azul-escuro e uma azul-claro, dobradas',
    oferta: 'COMPRE 1, LEVE 2',
    composicao: [
      'O que define esta direção: duas unidades dobradas lado a lado com um sinal de mais grande entre elas. A conta da oferta é desenhada, não só escrita.',
      'Superfície de madeira escura e fosca vista de cima, ocupando o quadro inteiro, com luz lateral suave.',
      'As duas peças ficam dobradas lado a lado, no mesmo tamanho e no mesmo alinhamento, com folga no meio.',
      'Entre elas, um sinal de mais claro e fino, maior que as letras da oferta e menor que uma peça.',
      'No alto: a marca pequena e clara. Embaixo: a oferta em uma linha de caixa alta pesada e clara.',
      'Esta peça não tem selo, etiqueta, preço, CTA nem moldura.',
    ],
  },
  {
    id: 'NOVA-16',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · seis unidades',
    nome: 'Gaveta aberta com as unidades enroladas',
    people: 'sem-pessoa',
    publico: 'Homem de 25 a 45 anos que repõe camisetas básicas de uma vez.',
    produto: 'seis camisetas lisas do mesmo modelo, enroladas, em branco, cinza-claro, cinza-escuro, preto, azul-marinho e verde-oliva',
    oferta: 'COMPRE 4, LEVE 6',
    composicao: [
      'O que define esta direção: uma gaveta aberta vista de cima, com as unidades enroladas em fileira. É a gaveta cheia que a oferta promete.',
      'Gaveta de madeira clara, vista de cima, ocupando quase todo o quadro. A borda da cômoda aparece escura em volta.',
      'As seis unidades ficam enroladas, deitadas lado a lado, cada uma com a cor inteira visível, sem sobreposição.',
      'Na borda escura acima da gaveta: a marca pequena e clara, e a oferta em uma linha de caixa alta pesada e clara.',
      'Esta peça não tem pessoa, selo, etiqueta, preço nem CTA.',
    ],
  },
  {
    id: 'NOVA-17',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · um produto',
    nome: 'Peça pendurada na parede com prendedor',
    people: 'sem-pessoa',
    publico: 'Homem de 25 a 45 anos que compra bermuda de linho para o verão.',
    produto: 'uma bermuda de linho cor areia, pendurada por um prendedor de madeira',
    oferta: 'LEVE 3, PAGUE 2',
    composicao: [
      'O que define esta direção: uma única peça pendurada numa parede lisa, como em um ateliê. Quase todo o quadro é respiro; o texto é curto.',
      'Parede lisa branca-quente, com textura leve de reboco e luz natural lateral projetando a sombra da peça na parede.',
      'A peça fica pendurada no centro por um prendedor de madeira preso a um prego, caindo reta, inteira e sem dobra.',
      'Embaixo, a marca pequena à esquerda e a oferta em uma linha de caixa alta pesada e escura à direita.',
      'Esta peça não tem selo, cartão, benefício escrito nem CTA.',
    ],
  },
  {
    id: 'NOVA-18',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · um produto',
    nome: 'Corpo em locação com faixa inferior de oferta',
    people: 'corpo-suporte',
    publico: 'Mulher de 25 a 45 anos que compra vestido leve para o dia a dia.',
    produto: 'um vestido midi liso, verde-sálvia, vestido por um corpo feminino sem rosto',
    oferta: 'COMPRE 1, LEVE 2',
    composicao: [
      'O que define esta direção: uma fotografia de locação ocupa o quadro quase inteiro, e a oferta fecha a peça numa faixa sólida embaixo. Foto e oferta não se misturam.',
      'Locação externa com muro de pedra clara e luz natural alta, fundo claro e sem detalhe.',
      'A pessoa caminha de frente, enquadrada do maxilar até logo abaixo da barra do vestido. O rosto não aparece. O vestido é o maior e o mais iluminado elemento e ocupa a maior parte da fotografia.',
      'Na base, uma faixa sólida escura de ponta a ponta, com a oferta em caixa alta pesada e clara, e a marca pequena à direita da oferta.',
      'Esta peça não tem selo, cartão, benefício escrito, acessório em destaque nem CTA.',
    ],
  },
  {
    id: 'NOVA-19',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · duas cores',
    nome: 'Veste uma, mostra a outra',
    people: 'corpo-suporte',
    publico: 'Homem de 25 a 45 anos que compra camisa de linho em mais de uma cor.',
    produto: 'duas camisas de linho masculinas do mesmo modelo — uma branca vestida por um homem e uma azul-clara dobrada na mão dele',
    oferta: 'COMPRE 1, LEVE 2',
    composicao: [
      'O que define esta direção: a pessoa veste uma unidade e a mão estende a segunda, dobrada, em direção à câmera. A segunda peça na mão é a oferta.',
      'Parede lisa clara, luz natural de janela vinda de um lado.',
      'A pessoa fica de frente num lado do quadro, enquadrada do maxilar até o quadril, em close. O rosto não aparece. A calça é lisa, escura e apagada, claramente secundária. A mão segura a camisa dobrada à frente do corpo, sem cobrir a camisa vestida.',
      'As duas camisas são os dois elementos mais nítidos do quadro.',
      'Na parede livre ao lado, alinhado à esquerda: a marca pequena e a oferta em duas linhas de caixa alta pesada.',
      'Esta peça não tem selo, cartão, benefício escrito nem CTA.',
    ],
  },
  {
    id: 'NOVA-20',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · cinco unidades',
    nome: 'Mão pegando uma unidade da fileira',
    people: 'corpo-suporte',
    publico: 'Adulto de 20 a 45 anos que compra meia em pacote.',
    produto: 'cinco pares de meia do mesmo modelo, enrolados, em branco, cinza, preto, azul-marinho e verde-oliva',
    oferta: 'COMPRE 3, LEVE 5',
    composicao: [
      'O que define esta direção: as unidades formam uma fileira regular vista de cima, e uma mão entra pela borda pegando uma delas. O gesto quebra a grade e dá escala.',
      'Tecido de linho claro e liso, visto de cima, ocupando o quadro inteiro. Luz natural lateral e sombras curtas.',
      'Os cinco pares ficam enrolados em fileira, no mesmo tamanho e com espaçamento regular. A mão, só até o pulso, entra por baixo e segura um deles, levemente deslocado da fileira.',
      'No alto, centralizado: a marca pequena e espaçada e a oferta em uma linha de caixa alta pesada.',
      'Esta peça não tem selo, etiqueta, embalagem, preço nem CTA.',
    ],
  },

  /* ---------- coleção · até X% · estética ---------- */
  {
    id: 'NOVA-21',
    caminho: 'coleção · até X% · estética · sem pessoa · três produtos',
    nome: 'Três peças em pedestais de pedra',
    people: 'sem-pessoa',
    publico: 'Mulher de 25 a 50 anos que compra semijoia como presente para si mesma.',
    produto: 'três semijoias douradas da mesma coleção: um colar de corrente fina, um par de brincos de argola e um anel largo',
    oferta: 'ATÉ 50% DE DESCONTO',
    composicao: [
      'O que define esta direção: cada peça da coleção ganha o seu próprio pedestal, e os três pedestais têm formas diferentes. É vitrine de joalheria sem virar grade.',
      'Fundo e superfície em pedra clara e fosca, contínuos, com luz suave de cima e sombras curtas.',
      'Três pedestais de pedra clara, de formas diferentes — um cilindro, um cubo e um bloco baixo — lado a lado. Cada um sustenta uma peça, inteira e nítida.',
      'As joias são os pontos mais brilhantes do quadro. Nada mais tem brilho metálico.',
      'No alto, centralizado e em escuro: a marca pequena e espaçada, e abaixo a oferta em uma linha de caixa alta pesada.',
      'Esta peça não tem pessoa, embalagem, selo, cartão nem CTA.',
    ],
  },
  {
    id: 'NOVA-22',
    caminho: 'coleção · até X% · estética · corpo sem rosto · três produtos',
    nome: 'Pulso e mão com a coleção inteira',
    people: 'corpo-suporte',
    publico: 'Mulher de 25 a 50 anos que monta combinação de acessórios dourados.',
    produto: 'três peças da mesma coleção dourada: um relógio de pulseira fina, uma pulseira rígida e um anel, todos usados na mesma mão',
    oferta: 'ATÉ 60% DE DESCONTO',
    composicao: [
      'O que define esta direção: uma única mão e pulso usam as três peças ao mesmo tempo. O corpo vira expositor da coleção.',
      'Fundo de tecido de seda claro e liso, levemente ondulado, com luz suave.',
      'A mão e o pulso entram em diagonal por uma borda, com os dedos relaxados. As três peças ficam no centro do quadro, todas visíveis e sem se esconder.',
      'As joias são os pontos mais brilhantes. Unhas curtas e neutras, sem esmalte colorido.',
      'No canto oposto à mão, alinhado à esquerda: a marca pequena, um filete curto e a oferta em duas linhas de caixa alta pesada e escura.',
      'Esta peça não tem selo, cartão, embalagem nem CTA.',
    ],
  },
  {
    id: 'NOVA-23',
    caminho: 'coleção · até X% · estética · sem pessoa · três produtos',
    nome: 'Look completo montado sobre a cama',
    people: 'sem-pessoa',
    publico: 'Homem de 25 a 45 anos que compra o look completo de uma vez.',
    produto: 'três peças da mesma coleção: uma camisa de linho branca, uma bermuda de sarja bege e um tênis de couro branco',
    oferta: 'ATÉ 70% DE DESCONTO',
    composicao: [
      'O que define esta direção: o look é montado como se estivesse vestido, peça abaixo de peça, deitado numa superfície e visto de cima.',
      'Lençol de algodão claro e levemente amassado, visto de cima, ocupando o quadro inteiro, com luz natural de janela.',
      'A camisa fica aberta na parte de cima, a bermuda logo abaixo como se continuasse o corpo, e o par de tênis na base. Cada peça aparece inteira.',
      'No canto superior livre, alinhado à esquerda e em escuro: a marca pequena e a oferta em duas linhas de caixa alta pesada.',
      'Esta peça não tem pessoa, selo, etiqueta, acessório extra nem CTA.',
    ],
  },
  {
    id: 'NOVA-24',
    caminho: 'coleção · até X% · estética · corpo sem rosto · um look · peça sem texto',
    nome: 'Conjunto vestido em luz de folhagem, sem texto',
    people: 'corpo-suporte',
    silent: true,
    publico: 'Mulher de 25 a 45 anos que compra roupa pela estética editorial.',
    produto: 'um conjunto de alfaiataria leve da mesma coleção, blazer e calça de linho cor areia, vestido por um corpo feminino sem rosto',
    composicao: [
      'O que define esta direção: o conjunto vestido, fotografado como editorial, sem nenhum texto. A luz e o caimento vendem sozinhos.',
      'Locação externa de parede branca caiada com sombra de folhagem projetada, luz de sol alta e contraste suave.',
      'A pessoa fica de frente, levemente de lado, enquadrada do maxilar até a canela. O rosto não aparece. O conjunto é o maior e o mais iluminado elemento e ocupa a maior parte da fotografia.',
      'Sem bolsa, sem óculos, sem joia, sem acessório.',
    ],
  },

  /* ---------- coleção · compre X leve Y · estética ---------- */
  {
    id: 'NOVA-25',
    caminho: 'coleção · compre X leve Y · estética · sem pessoa · três produtos',
    nome: 'Três peças no cabideiro de parede',
    people: 'sem-pessoa',
    publico: 'Homem de 25 a 45 anos que monta o guarda-roupa com peças da mesma coleção.',
    produto: 'três peças diferentes da mesma coleção: uma jaqueta de sarja verde-oliva, uma camisa lisa bege e uma calça chino cáqui',
    oferta: 'COMPRE 2, LEVE 3',
    composicao: [
      'O que define esta direção: três peças diferentes penduradas lado a lado em ganchos de parede, cada uma no seu cabide. É o guarda-roupa aberto da coleção.',
      'Parede lisa em tom claro e quente, com uma régua de madeira escura na horizontal segurando três ganchos.',
      'As três peças pendem de frente, no mesmo nível e com folga, sem se sobrepor, cada uma inteira.',
      'Embaixo, na parede livre, centralizado: a oferta em uma linha de caixa alta pesada e escura, e a marca pequena abaixo dela.',
      'Esta peça não tem pessoa, selo, etiqueta, preço nem CTA.',
    ],
  },

  /* ---------- coleção · desconto progressivo · estética (a escada precisa aparecer) ---------- */
  {
    id: 'NOVA-26',
    caminho: 'coleção · progressivo · estética · sem pessoa · três produtos',
    nome: 'Três pedestais em alturas crescentes',
    people: 'sem-pessoa',
    publico: 'Mulher de 25 a 45 anos que compra cuidado com a pele em rotina completa.',
    produto: 'três produtos de uma mesma linha de skincare em frascos de vidro fosco claro, sem rótulo de marca: um sérum com conta-gotas, um creme em pote e um tônico em frasco alto',
    oferta: '1 ITEM 10% OFF · 2 ITENS 20% OFF · 3 ITENS 30% OFF',
    composicao: [
      'O que define esta direção: a escada do desconto é física. Três pedestais sobem de um lado para o outro, cada um com um produto, e cada degrau carrega o seu percentual.',
      'Fundo claro e quente, contínuo, com luz suave vinda de cima e sombras curtas.',
      'Três pedestais cilíndricos de pedra clara, lado a lado, cada um mais alto que o anterior. Um produto em cima de cada pedestal, inteiro e nítido.',
      'Na face de cada pedestal, em escuro: a quantidade em corpo pequeno e o percentual em caixa alta pesada logo abaixo. O último percentual é o maior dos três.',
      'No alto, alinhado à esquerda: a marca pequena e uma headline curta de uma linha dizendo que quanto mais leva, mais economiza.',
      'Esta peça não tem pessoa, selo, cartão, preço nem CTA.',
    ],
  },
  {
    id: 'NOVA-27',
    caminho: 'coleção · progressivo · estética · corpo sem rosto · três degraus',
    nome: 'Três faixas, mãos com uma, duas e três peças',
    people: 'corpo-suporte',
    publico: 'Adulto de 20 a 40 anos que compra camiseta básica de várias cores da mesma coleção.',
    produto: 'camisetas lisas dobradas de uma mesma coleção, em branco, preto e cinza, seguradas nas mãos',
    oferta: '1 PEÇA 10% OFF · 2 PEÇAS 20% OFF · 3 PEÇAS 30% OFF',
    composicao: [
      'O que define esta direção: o quadro é dividido em três faixas horizontais, e em cada uma um par de mãos segura uma pilha maior — uma peça, duas, três. A escada do desconto é contada nas mãos.',
      'Fundo claro e liso nas três faixas, separadas por filetes finos escuros.',
      'Em cada faixa, duas mãos entram por um lado segurando a pilha dobrada. Só mãos e pulsos aparecem. As pilhas crescem de cima para baixo.',
      'Do outro lado de cada faixa, alinhado à direita: a quantidade em corpo pequeno e o percentual em caixa alta pesada. O percentual da última faixa é o maior.',
      'A marca pequena fica no topo da primeira faixa.',
      'Esta peça não tem selo, cartão, preço nem CTA.',
    ],
  },
  {
    id: 'NOVA-28',
    caminho: 'coleção · progressivo · estética · sem pessoa · três produtos',
    nome: 'Escada de pedra, uma peça por degrau',
    people: 'sem-pessoa',
    publico: 'Mulher de 25 a 45 anos que compra bolsa, sandália e cinto da mesma coleção.',
    produto: 'três itens da mesma coleção em couro caramelo: uma bolsa de ombro, uma sandália de tiras e um cinto enrolado',
    oferta: '1 ITEM 15% OFF · 2 ITENS 25% OFF · 3 ITENS 35% OFF',
    composicao: [
      'O que define esta direção: uma escada real vira a escada do desconto. Cada degrau segura um produto com o seu percentual, subindo.',
      'Escada externa de pedra clara, vista de lado em três quartos, luz de sol alta, parede clara ao fundo.',
      'Três degraus em sequência, um produto inteiro e nítido em cada degrau, subindo da frente para trás.',
      'Os produtos são os elementos mais nítidos e mais iluminados do quadro.',
      'Na face vertical de cada degrau, em escuro: o percentual em caixa alta pesada, crescendo com o degrau. A marca pequena fica no alto.',
      'Esta peça não tem selo, cartão, preço nem CTA.',
    ],
  },

  /* ---------- produto único · até X% · função ---------- */
  {
    id: 'NOVA-29',
    caminho: 'produto único · até X% · função · corpo sem rosto · duas cores',
    nome: 'Mão com o produto e tópicos em linha fina',
    people: 'corpo-suporte',
    publico: 'Adulto de 25 a 50 anos que quer trocar a escova de dentes manual pela elétrica.',
    produto: 'duas escovas de dentes elétricas do mesmo modelo, uma branca e uma preta — a branca na mão, a preta de pé na base de carregamento',
    oferta: 'ATÉ 50% DE DESCONTO',
    composicao: [
      'O que define esta direção: a mão mostra o produto de perto, a segunda cor fica em pé na base, e o argumento vem em três tópicos com ícone de linha fina.',
      'Fundo de banheiro claro, azulejo branco liso, desfocado.',
      'A mão aparece só até o pulso, segurando a escova branca em pé. A preta fica em pé na base, ao lado, um pouco mais atrás.',
      'Do outro lado do quadro, empilhados e alinhados à esquerda: a marca pequena no alto; três linhas curtas de benefício, cada uma com um ícone de linha fina solto; e a oferta na base, com o número em corpo grande.',
      'Esta peça não tem selo, cartão, moldura, estrela de avaliação nem CTA.',
    ],
  },
  {
    id: 'NOVA-30',
    caminho: 'produto único · até X% · função · corpo sem rosto · três cores',
    nome: 'Mão na bancada com as cores ao lado',
    people: 'corpo-suporte',
    publico: 'Adulto de 25 a 45 anos que prepara vitamina e shake em casa, sem tempo.',
    produto: 'três mini liquidificadores portáteis do mesmo modelo, em branco, verde-menta e rosa-claro — um na mão, dois em pé na bancada',
    oferta: 'ATÉ 60% DE DESCONTO',
    composicao: [
      'O que define esta direção: uma mão ergue o produto cheio de vitamina numa cozinha real, e as outras cores estão na bancada, na mesma luz. Uso e variedade na mesma foto.',
      'Cozinha clara, bancada de pedra clara, parede lisa clara ao fundo, luz de janela.',
      'Só a mão e o antebraço aparecem, entrando pela borda e segurando um liquidificador cheio. Os outros dois ficam em pé na bancada, ao lado, inteiros.',
      'Os produtos são os elementos mais nítidos do quadro.',
      'Na parede livre, alinhado à esquerda: a marca pequena, uma headline de duas linhas com o benefício principal em caixa alta pesada, e a oferta em uma linha.',
      'Esta peça não tem selo, cartão, ícone nem CTA.',
    ],
  },
  {
    id: 'NOVA-31',
    caminho: 'produto único · até X% · função · sem pessoa · um produto',
    nome: 'Produto ao centro com legendas apontando',
    people: 'sem-pessoa',
    publico: 'Adulto de 20 a 40 anos que anda de transporte público com notebook.',
    produto: 'uma mochila antifurto cinza-grafite, com zíper escondido e entrada USB lateral',
    oferta: 'ATÉ 60% DE DESCONTO',
    composicao: [
      'O que define esta direção: o produto no centro e três legendas curtas ligadas a partes dele por linhas finas. É a peça que explica o produto apontando para ele.',
      'Fundo cinza muito claro, liso e contínuo.',
      'A mochila aparece em três quartos, no centro, inteira e com sombra de contato curta.',
      'Três legendas de duas ou três palavras cada, em escuro, ligadas por linhas finas retas às partes que descrevem. As linhas não cruzam o produto.',
      'No alto, centralizado: a marca pequena. Embaixo, centralizado: a oferta em uma linha de caixa alta pesada.',
      'Esta peça não tem pessoa, selo, cartão, moldura nem CTA.',
    ],
  },

  /* ---------- produto único · compre X leve Y · função ---------- */
  {
    id: 'NOVA-32',
    caminho: 'produto único · compre X leve Y · função · sem pessoa · duas unidades',
    nome: 'Duas unidades com a conta desenhada',
    people: 'sem-pessoa',
    publico: 'Adulto de 25 a 55 anos que quer luz de emergência em casa.',
    produto: 'duas lanternas recarregáveis do mesmo modelo, pretas, em pé',
    oferta: 'COMPRE 1, LEVE 2',
    composicao: [
      'O que define esta direção: duas unidades idênticas em pé lado a lado, com “1 + 1” entre elas e uma linha de benefício embaixo.',
      'Fundo claro e liso, cinza muito claro, contínuo.',
      'As duas lanternas ficam em pé, no mesmo tamanho, com folga no meio. Entre elas, “1 + 1” em caixa alta pesada escura.',
      'No alto, centralizado: a marca pequena e a oferta em uma linha de caixa alta pesada.',
      'Embaixo, uma única linha pequena e espaçada com três benefícios separados por pontos.',
      'Esta peça não tem pessoa, selo, ícone, embalagem nem CTA.',
    ],
  },
  {
    id: 'NOVA-33',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · duas unidades',
    nome: 'Os dois joelhos, uma unidade em cada',
    people: 'corpo-suporte',
    publico: 'Adulto de 35 a 60 anos que sente dor no joelho ao caminhar ou subir escada.',
    produto: 'duas joelheiras de compressão do mesmo modelo, pretas, uma em cada joelho',
    oferta: 'COMPRE 1, LEVE 2',
    composicao: [
      'O que define esta direção: o produto vem em par porque o corpo tem dois. As duas pernas aparecem lado a lado, cada joelho com uma unidade.',
      'Fundo claro e liso, parede de estúdio clara.',
      'As pernas aparecem de frente, lado a lado, enquadradas do meio da coxa até o meio da canela. A bermuda é lisa, neutra e claramente secundária. As joelheiras são o que tem mais contraste.',
      'Na faixa lateral, alinhado à esquerda: a marca pequena, três linhas curtas de benefício separadas por filetes finos e a oferta na base, em caixa alta pesada.',
      'Esta peça não tem selo, cartão, moldura, estrela de avaliação nem CTA.',
    ],
  },
  {
    id: 'NOVA-34',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · duas unidades',
    nome: 'Mão afundando um dos dois travesseiros',
    people: 'corpo-suporte',
    publico: 'Adulto de 30 a 55 anos que acorda com dor no pescoço.',
    produto: 'dois travesseiros ortopédicos do mesmo modelo, brancos, lado a lado na cama',
    oferta: 'COMPRE 1, LEVE 2',
    composicao: [
      'O que define esta direção: os dois travesseiros lado a lado na cama, e uma mão afunda um deles mostrando a espuma que volta ao formato. O par é a oferta; o gesto é o argumento.',
      'Cama arrumada com lençol cinza-claro liso, vista de cima em diagonal, luz de manhã vinda de janela lateral.',
      'Só a mão e o pulso aparecem, entrando pela borda e pressionando o centro de um travesseiro. O outro fica intacto ao lado. Os dois travesseiros são o que tem mais brilho no quadro.',
      'Na área livre do lençol, no alto: a marca pequena, uma headline de uma linha com o benefício e a oferta em caixa alta pesada.',
      'Esta peça não tem selo, cartão, ícone nem CTA.',
    ],
  },
  {
    id: 'NOVA-35',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · um produto',
    nome: 'Perna com o produto e faixa escura de oferta',
    people: 'corpo-suporte',
    publico: 'Mulher de 30 a 60 anos que passa o dia em pé e sente as pernas cansadas.',
    produto: 'uma meia de compressão até o joelho, cor nude, em uso numa perna',
    oferta: 'LEVE 3, PAGUE 2',
    composicao: [
      'O que define esta direção: uma perna em perfil mostra o produto em uso, e uma faixa escura embaixo junta a oferta e os benefícios.',
      'Fundo claro e liso, cinza-claro quente.',
      'A perna aparece em perfil, do joelho até o pé descalço, apoiada na ponta. A meia é o elemento mais nítido.',
      'Na base, uma faixa sólida escura de ponta a ponta: a oferta em caixa alta pesada e clara de um lado, e três benefícios curtos empilhados do outro.',
      'A marca pequena fica no alto, alinhada à esquerda.',
      'Esta peça não tem selo, cartão, ícone nem CTA.',
    ],
  },
  {
    id: 'NOVA-36',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · um produto',
    nome: 'Nuca em movimento com headline de benefício',
    people: 'corpo-suporte',
    publico: 'Homem de 20 a 45 anos que corre ao ar livre e quer continuar ouvindo o ambiente.',
    produto: 'um fone de condução óssea preto, em uso, com o arco passando atrás da nuca',
    oferta: 'COMPRE 1, LEVE 2',
    composicao: [
      'O que define esta direção: o produto em uso visto de costas, durante uma corrida real, e uma headline de benefício sobre o céu claro.',
      'Parque aberto com céu claro e liso ocupando a parte de cima do quadro.',
      'A pessoa é vista de costas, de perto: nuca, orelhas e ombros, com o arco do fone passando atrás da nuca, nítido e bem iluminado. Camiseta lisa em tom neutro. Fundo levemente desfocado.',
      'Sobre o céu, alinhado à esquerda: a marca pequena, uma headline de duas linhas com o benefício em caixa alta pesada escura, e a oferta em uma linha abaixo.',
      'Esta peça não tem selo, cartão, ícone nem CTA.',
    ],
  },
];
