/*
 * Direções novas, no formato que o app usa de verdade.
 *
 * Cada item carrega duas coisas:
 * - o CONTEXTO que o ChatGPT capturaria da loja (produto, variações, itens, benefícios,
 *   público, argumento), porque o prompt do app só existe depois do contexto;
 * - a RECEITA, em bullets, no formato de `testedDirections` (diretriz 24): abre com
 *   “O que define esta direção:”, segue estrutura, produto, pessoa, texto, luz e cor,
 *   declara ausências e o que acontece quando o conteúdo muda — e não repete o que
 *   o núcleo já garante (foco no produto, tipografia, presença humana).
 *
 * Quando a imagem for aprovada, a receita entra em `testedDirections` sem reescrita.
 */
export const lote = [
  /* ---------- produto único · compre X leve Y · estética ---------- */
  {
    id: 'NOVA-12',
    nome: 'Grade de quatro closes, uma cor por módulo',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · quatro cores',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Camiseta básica masculina de algodão', categoria: 'vestuário masculino',
    variantes: ['branca', 'preta', 'azul-marinho', 'verde-oliva'],
    detalhes: 'gola careca, manga curta, malha lisa sem estampa e sem logo',
    publico: 'Homem de 20 a 40 anos que compra camiseta básica em quantidade.',
    oferta: 'COMPRE 3, LEVE 4',
    people: 'corpo-suporte', slots: 4, fillsWithVariants: true,
    receita: [
      'O que define esta direção: o quadro é uma grade de quatro módulos iguais, dois por dois, e cada módulo mostra a mesma camiseta vestida numa cor diferente. A repetição do mesmo produto é o argumento do “leve mais”.',
      'Os quatro módulos repetem o mesmo fundo de estúdio claro e liso, a mesma luz frontal suave e o mesmo enquadramento, separados por respiros finos claros.',
      'Em cada módulo a pessoa fica de frente, enquadrada do maxilar até o quadril, em close. Braços relaxados ao lado do corpo. A calça é a mesma nos quatro módulos, lisa, neutra e escura.',
      'Na base, uma faixa sólida escura atravessa o quadro de ponta a ponta com a oferta em caixa alta pesada e clara, e a marca pequena ao lado. É o único bloco de texto da peça.',
      'Esta peça não tem headline, benefício, selo, ícone, preço ou CTA.',
      'Com menos cores confirmadas, a grade usa menos módulos e cada um fica maior; com uma cor só, a foto ocupa o quadro inteiro acima da faixa.',
    ],
  },
  {
    id: 'NOVA-13',
    nome: 'Uma mão erguendo três cabides',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · três cores',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Camisa polo masculina de piquet', categoria: 'vestuário masculino',
    variantes: ['branca', 'azul-marinho', 'verde-escuro'],
    detalhes: 'gola polo, três botões, manga curta, piquet liso sem logo',
    publico: 'Homem de 25 a 45 anos que compra camisa polo em mais de uma cor.',
    oferta: 'COMPRE 2, LEVE 3',
    people: 'corpo-suporte', slots: 3, fillsWithVariants: true,
    receita: [
      'O que define esta direção: uma única mão entra pelo alto do quadro segurando três cabides de uma vez, e as três cores pendem abertas em leque. É o gesto de quem já decidiu levar todas.',
      'Fundo de parede lisa, clara e quente, contínuo, sem cenário. Luz lateral suave e sombra curta das peças na parede.',
      'Só a mão e o pulso aparecem. A peça da frente fica inteira; as outras duas aparecem pela lateral, deslocadas, cada cor bem separada da vizinha.',
      'Embaixo, centralizados: a oferta em uma linha de caixa alta pesada e escura e, logo abaixo, a marca pequena e espaçada.',
      'Esta peça não tem headline, benefício, etiqueta, selo ou CTA.',
      'Com duas cores confirmadas, a mão segura dois cabides; com uma só, um cabide e a peça fica maior.',
    ],
  },
  {
    id: 'NOVA-14',
    nome: 'Close vestido na frente da oferta gigante',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · um produto',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Camiseta masculina de algodão pesado', categoria: 'vestuário masculino',
    variantes: ['areia'],
    detalhes: 'gola careca canelada, manga curta, malha encorpada lisa sem logo',
    publico: 'Homem de 20 a 40 anos que compra camiseta pesada de algodão.',
    oferta: 'COMPRE 2, LEVE 3',
    people: 'corpo-suporte', slots: 1,
    receita: [
      'O que define esta direção: a oferta em letras enormes atravessa o fundo e a pessoa vestindo o produto fica na frente dela. Texto e foto ocupam o mesmo plano, e a quantidade da oferta vive só no texto.',
      'Fundo de estúdio escuro, liso e contínuo, com luz lateral recortando o corpo.',
      'A pessoa fica de frente, no centro, enquadrada do maxilar até o quadril, em close. A calça é lisa, escura e apagada.',
      'A oferta ocupa duas linhas em caixa alta pesada e clara, atrás do corpo; o corpo cobre parte das letras sem impedir a leitura das palavras.',
      'A marca pequena e clara fica no pé do quadro, centralizada.',
      'Esta peça não tem headline separada, benefício, selo ou CTA.',
    ],
  },
  {
    id: 'NOVA-15',
    nome: 'Duas unidades dobradas com um sinal de mais',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · duas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Calça jeans reta', categoria: 'vestuário',
    variantes: ['azul-escuro', 'azul-claro'],
    detalhes: 'modelagem reta, cinco bolsos, lavagem uniforme, sem etiqueta aparente',
    publico: 'Adulto de 25 a 45 anos que compra calça jeans e já leva a segunda.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'sem-pessoa', slots: 2, fillsWithVariants: true,
    receita: [
      'O que define esta direção: duas unidades dobradas lado a lado com um sinal de mais grande entre elas. A conta da oferta é desenhada, não só escrita.',
      'Superfície de madeira escura e fosca vista de cima, ocupando o quadro inteiro, com luz lateral suave.',
      'As duas peças ficam dobradas lado a lado, no mesmo tamanho e no mesmo alinhamento, com folga no meio.',
      'Entre elas, um sinal de mais claro e fino, maior que as letras da oferta e menor que uma peça.',
      'No alto, a marca pequena e clara. Embaixo, a oferta em uma linha de caixa alta pesada e clara.',
      'Esta peça não tem pessoa, headline, etiqueta, selo, preço ou CTA.',
      'Com uma única cor confirmada, as duas unidades são idênticas.',
    ],
  },
  {
    id: 'NOVA-16',
    nome: 'Gaveta aberta com as unidades enroladas',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · seis unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Camiseta básica masculina de algodão', categoria: 'vestuário masculino',
    variantes: ['branca', 'cinza-clara', 'cinza-escura', 'preta', 'azul-marinho', 'verde-oliva'],
    detalhes: 'gola careca, manga curta, malha lisa sem estampa e sem logo',
    publico: 'Homem de 25 a 45 anos que repõe camisetas básicas de uma vez.',
    oferta: 'COMPRE 4, LEVE 6',
    people: 'sem-pessoa', slots: 6, fillsWithVariants: true, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: uma gaveta aberta vista de cima, com as unidades enroladas em fileira. É a gaveta cheia que a oferta promete.',
      'Gaveta de madeira clara, vista de cima, ocupando quase todo o quadro. A borda da cômoda aparece escura em volta.',
      'As unidades ficam enroladas e deitadas lado a lado, cada uma com a cor inteira visível, sem sobreposição.',
      'Na borda escura acima da gaveta: a marca pequena e clara e a oferta em uma linha de caixa alta pesada e clara.',
      'Esta peça não tem pessoa, headline, etiqueta, embalagem, selo ou CTA.',
      'Com menos cores confirmadas, a fileira repete as cores reais até encher a gaveta; nenhuma cor nova é inventada.',
    ],
  },
  {
    id: 'NOVA-17',
    nome: 'Peça pendurada na parede com prendedor',
    caminho: 'produto único · compre X leve Y · estética · sem pessoa · um produto',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Bermuda masculina de linho', categoria: 'vestuário masculino',
    variantes: ['areia'],
    detalhes: 'cós com cordão, dois bolsos laterais, linho liso sem logo',
    publico: 'Homem de 25 a 45 anos que compra bermuda de linho para o verão.',
    oferta: 'LEVE 3, PAGUE 2',
    people: 'sem-pessoa', slots: 1,
    receita: [
      'O que define esta direção: uma única peça pendurada numa parede lisa, como em um ateliê. Quase todo o quadro é respiro, e o texto é curto.',
      'Parede lisa branca-quente, com textura leve de reboco e luz natural lateral projetando a sombra da peça na parede.',
      'A peça fica pendurada no centro por um prendedor de madeira preso a um prego, caindo reta, inteira e sem dobra.',
      'Embaixo, na mesma linha: a marca pequena à esquerda e a oferta em caixa alta pesada e escura à direita.',
      'Esta peça não tem pessoa, headline, benefício, selo ou CTA.',
    ],
  },
  {
    id: 'NOVA-18',
    nome: 'Vestido em locação com faixa de oferta',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · um produto',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Vestido midi liso', categoria: 'vestuário feminino',
    variantes: ['verde-sálvia'],
    detalhes: 'alças finas, saia fluida até o meio da canela, tecido liso sem estampa',
    publico: 'Mulher de 25 a 45 anos que compra vestido leve para o dia a dia.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'corpo-suporte', slots: 1,
    receita: [
      'O que define esta direção: uma fotografia de locação ocupa quase o quadro inteiro e a oferta fecha a peça numa faixa sólida embaixo. Foto e texto não se misturam.',
      'Locação externa com muro de pedra clara e luz natural alta; o fundo é claro e quase sem detalhe.',
      'A pessoa caminha de frente, enquadrada do maxilar até logo abaixo da barra do vestido. O vestido ocupa a maior parte da fotografia.',
      'Na base, uma faixa sólida escura de ponta a ponta com a oferta em caixa alta pesada e clara, e a marca pequena ao lado da oferta.',
      'Esta peça não tem headline, benefício, selo, bolsa ou CTA.',
    ],
  },
  {
    id: 'NOVA-19',
    nome: 'Veste uma, mostra a outra',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · duas cores',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Camisa masculina de linho', categoria: 'vestuário masculino',
    variantes: ['branca', 'azul-clara'],
    detalhes: 'gola italiana, manga longa, botões na frente, linho liso sem logo',
    publico: 'Homem de 25 a 45 anos que compra camisa de linho em mais de uma cor.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'corpo-suporte', slots: 2, fillsWithVariants: true,
    receita: [
      'O que define esta direção: a pessoa veste uma unidade e estende a segunda, dobrada, em direção à câmera. A segunda peça na mão é a oferta.',
      'Parede lisa clara, contínua, com luz natural de janela vinda de um lado.',
      'A pessoa fica de frente num lado do quadro, enquadrada do maxilar até o quadril, em close. A mão segura a outra cor dobrada à frente do corpo, sem cobrir a camisa vestida. A calça é lisa, escura e apagada.',
      'Na parede livre do outro lado, alinhados à esquerda: a marca pequena e a oferta em duas linhas de caixa alta pesada. A parede continua atrás do texto, sem painel.',
      'Esta peça não tem headline, benefício, selo ou CTA.',
      'Com uma única cor confirmada, a peça dobrada é da mesma cor da vestida.',
    ],
  },
  {
    id: 'NOVA-20',
    nome: 'Mão pegando uma unidade da fileira',
    caminho: 'produto único · compre X leve Y · estética · corpo sem rosto · cinco unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Meia cano médio de algodão', categoria: 'vestuário',
    variantes: ['branca', 'cinza', 'preta', 'azul-marinho', 'verde-oliva'],
    detalhes: 'cano médio canelado, malha lisa sem logo',
    publico: 'Adulto de 20 a 45 anos que compra meia em pacote.',
    oferta: 'COMPRE 3, LEVE 5',
    people: 'corpo-suporte', slots: 5, fillsWithVariants: true, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: as unidades formam uma fileira regular vista de cima, e uma mão entra pela borda pegando uma delas. O gesto quebra a grade e dá escala.',
      'Tecido de linho claro e liso, visto de cima, ocupando o quadro inteiro, com luz natural lateral e sombras curtas.',
      'Os pares ficam enrolados em fileira, do mesmo tamanho e com espaçamento regular. A mão, só até o pulso, entra por baixo e segura um deles, levemente deslocado da fileira.',
      'No alto, centralizados: a marca pequena e espaçada e a oferta em uma linha de caixa alta pesada.',
      'Esta peça não tem headline, etiqueta, embalagem, selo ou CTA.',
      'Com menos cores confirmadas, a fileira repete as cores reais; nenhuma cor nova é inventada.',
    ],
  },

  /* ---------- coleção · até X% · estética ---------- */
  {
    id: 'NOVA-21',
    nome: 'Três peças em pedestais de pedra',
    caminho: 'coleção · até X% · estética · sem pessoa · três produtos',
    mode: 'collection', mech: 'percentual', argumento: 'estetica',
    alvo: 'Coleção de semijoias douradas', categoria: 'semijoias',
    itens: ['colar de corrente fina dourada', 'par de brincos de argola dourados', 'anel largo dourado'],
    publico: 'Mulher de 25 a 50 anos que compra semijoia para si mesma.',
    oferta: 'ATÉ 50% DE DESCONTO',
    people: 'sem-pessoa', slots: 3,
    receita: [
      'O que define esta direção: cada peça da coleção ganha o seu próprio pedestal, e os pedestais têm formas diferentes entre si. É vitrine de joalheria sem virar grade.',
      'Fundo e superfície em pedra clara e fosca, contínuos, com luz suave vinda de cima e sombras curtas.',
      'Três pedestais de pedra clara lado a lado — um cilindro, um cubo e um bloco baixo —, cada um sustentando uma peça inteira.',
      'As joias são o único brilho metálico do quadro.',
      'No alto, centralizados e em escuro: a marca pequena e espaçada e a oferta em uma linha de caixa alta pesada.',
      'Esta peça não tem pessoa, embalagem, selo, cartão ou CTA.',
      'Com menos itens confirmados, sobram menos pedestais e cada um fica maior.',
    ],
  },
  {
    id: 'NOVA-22',
    nome: 'Uma mão usando a coleção inteira',
    caminho: 'coleção · até X% · estética · corpo sem rosto · três produtos',
    mode: 'collection', mech: 'percentual', argumento: 'estetica',
    alvo: 'Coleção de acessórios dourados', categoria: 'acessórios',
    itens: ['relógio de pulseira fina dourada', 'pulseira rígida dourada', 'anel dourado liso'],
    publico: 'Mulher de 25 a 50 anos que combina acessórios dourados.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'corpo-suporte', slots: 3,
    receita: [
      'O que define esta direção: uma única mão e pulso usam as três peças ao mesmo tempo. O corpo vira expositor da coleção.',
      'Fundo de seda clara e lisa, levemente ondulada, com luz suave.',
      'A mão e o pulso entram em diagonal por uma borda, com os dedos relaxados. As três peças ficam no centro, todas visíveis, nenhuma escondendo a outra. Unhas curtas e neutras.',
      'No canto oposto à mão, alinhados à esquerda: a marca pequena, um filete curto e a oferta em duas linhas de caixa alta pesada e escura.',
      'Esta peça não tem selo, cartão, embalagem ou CTA.',
      'Com menos itens confirmados, a mão usa só os itens reais.',
    ],
  },
  {
    id: 'NOVA-23',
    nome: 'Look completo montado sobre a cama',
    caminho: 'coleção · até X% · estética · sem pessoa · três produtos',
    mode: 'collection', mech: 'percentual', argumento: 'estetica',
    alvo: 'Coleção masculina de verão', categoria: 'vestuário e calçado masculino',
    itens: ['camisa de linho branca', 'bermuda de sarja bege', 'tênis de couro branco'],
    publico: 'Homem de 25 a 45 anos que compra o look completo de uma vez.',
    oferta: 'ATÉ 70% DE DESCONTO',
    people: 'sem-pessoa', slots: 3,
    receita: [
      'O que define esta direção: o look é montado como se estivesse vestido, peça abaixo de peça, deitado numa cama e visto de cima.',
      'Lençol de algodão claro e levemente amassado ocupando o quadro inteiro, com luz natural de janela.',
      'A camisa aberta em cima, a bermuda logo abaixo continuando o corpo e o calçado na base. Cada peça aparece inteira.',
      'No canto superior livre, alinhados à esquerda e em escuro: a marca pequena e a oferta em duas linhas de caixa alta pesada.',
      'Esta peça não tem pessoa, selo, etiqueta, acessório extra ou CTA.',
      'Com menos itens confirmados, o look fica mais curto e o lençol mais livre; nenhuma peça é inventada para completá-lo.',
    ],
  },
  {
    id: 'NOVA-24',
    nome: 'Conjunto vestido em luz de folhagem',
    caminho: 'coleção · até X% · estética · corpo sem rosto · um look · peça sem texto',
    mode: 'collection', mech: 'percentual', argumento: 'estetica',
    alvo: 'Coleção de alfaiataria leve feminina', categoria: 'vestuário feminino',
    itens: ['blazer de linho cor areia', 'calça de linho cor areia'],
    publico: 'Mulher de 25 a 45 anos que compra roupa pela estética editorial.',
    oferta: 'ATÉ 70% DE DESCONTO',
    people: 'corpo-suporte', slots: 2, silent: true,
    receita: [
      'O que define esta direção: o conjunto vestido fotografado como editorial, sem nenhum texto. A luz filtrada e o caimento vendem sozinhos.',
      'Locação externa de parede branca caiada com sombra de folhagem projetada, luz de sol alta e contraste suave.',
      'A pessoa fica de frente, levemente de lado, enquadrada do maxilar até a canela. O conjunto ocupa a maior parte da fotografia.',
      'Sem bolsa, óculos, joia ou acessório.',
      'Esta peça não tem texto, marca, selo, borda ou efeito gráfico.',
    ],
  },

  /* ---------- coleção · compre X leve Y · estética ---------- */
  {
    id: 'NOVA-25',
    nome: 'Três peças no cabideiro de parede',
    caminho: 'coleção · compre X leve Y · estética · sem pessoa · três produtos',
    mode: 'collection', mech: 'leve-mais', argumento: 'estetica',
    alvo: 'Coleção masculina de meia-estação', categoria: 'vestuário masculino',
    itens: ['jaqueta de sarja verde-oliva', 'camisa lisa bege', 'calça chino cáqui'],
    publico: 'Homem de 25 a 45 anos que monta o guarda-roupa com peças da mesma coleção.',
    oferta: 'COMPRE 2, LEVE 3',
    people: 'sem-pessoa', slots: 3,
    receita: [
      'O que define esta direção: peças diferentes penduradas lado a lado em ganchos de parede, cada uma no seu cabide. É o guarda-roupa aberto da coleção.',
      'Parede lisa clara e quente, atravessada por uma régua de madeira escura que segura os ganchos.',
      'As peças pendem de frente, no mesmo nível e com folga entre elas, cada uma inteira.',
      'Embaixo, na parede livre, centralizados: a oferta em uma linha de caixa alta pesada e escura e a marca pequena abaixo dela.',
      'Esta peça não tem pessoa, headline, etiqueta, selo, preço ou CTA.',
      'Com menos itens confirmados, a régua segura menos ganchos e fica mais curta.',
    ],
  },

  /* ---------- coleção · desconto progressivo · estética ---------- */
  {
    id: 'NOVA-26',
    nome: 'Três pedestais em alturas crescentes',
    caminho: 'coleção · progressivo · estética · sem pessoa · três produtos',
    mode: 'collection', mech: 'progressivo', argumento: 'estetica',
    alvo: 'Linha de cuidados com a pele', categoria: 'cosméticos',
    itens: ['sérum em frasco de vidro fosco com conta-gotas', 'creme em pote de vidro fosco', 'tônico em frasco alto de vidro fosco'],
    publico: 'Mulher de 25 a 45 anos que monta uma rotina completa de cuidado com a pele.',
    oferta: '1 ITEM 10% OFF · 2 ITENS 20% OFF · 3 ITENS 30% OFF',
    people: 'sem-pessoa', slots: 3,
    receita: [
      'O que define esta direção: a escada do desconto é física. Pedestais sobem de um lado para o outro, cada um com um produto, e cada degrau carrega o seu percentual.',
      'Fundo claro e quente, contínuo, com luz suave vinda de cima e sombras curtas.',
      'Pedestais cilíndricos de pedra clara lado a lado, cada um mais alto que o anterior, com um produto inteiro em cima de cada.',
      'Na face de cada pedestal, em escuro: a quantidade em corpo pequeno e o percentual em caixa alta pesada logo abaixo. O último percentual é o maior.',
      'No alto, alinhados à esquerda: a marca pequena e uma headline de uma linha dizendo que quanto mais leva, mais economiza.',
      'Esta peça não tem pessoa, selo, cartão, preço ou CTA.',
      'Com mais degraus na oferta, entram mais pedestais; com menos itens, um item pode aparecer em mais de um degrau.',
    ],
  },
  {
    id: 'NOVA-27',
    nome: 'Três faixas, mãos com uma, duas e três peças',
    caminho: 'coleção · progressivo · estética · corpo sem rosto · três degraus',
    mode: 'collection', mech: 'progressivo', argumento: 'estetica',
    alvo: 'Coleção de camisetas básicas', categoria: 'vestuário',
    itens: ['camiseta básica branca', 'camiseta básica preta', 'camiseta básica cinza'],
    publico: 'Adulto de 20 a 40 anos que compra camisetas básicas de várias cores.',
    oferta: '1 PEÇA 10% OFF · 2 PEÇAS 20% OFF · 3 PEÇAS 30% OFF',
    people: 'corpo-suporte', slots: 3,
    receita: [
      'O que define esta direção: o quadro é dividido em três faixas horizontais, e em cada uma um par de mãos segura uma pilha maior — uma peça, duas, três. A escada do desconto é contada nas mãos.',
      'As três faixas têm o mesmo fundo claro e liso, separadas por filetes finos escuros.',
      'Em cada faixa, duas mãos entram por um lado segurando a pilha dobrada; só mãos e pulsos aparecem. As pilhas crescem de cima para baixo.',
      'Do outro lado de cada faixa, alinhados à direita: a quantidade em corpo pequeno e o percentual em caixa alta pesada. O percentual da última faixa é o maior.',
      'A marca pequena fica no topo da primeira faixa.',
      'Esta peça não tem headline, selo, cartão, preço ou CTA.',
      'Com mais degraus na oferta, entram mais faixas e cada uma fica mais baixa.',
    ],
  },
  {
    id: 'NOVA-28',
    nome: 'Escada de pedra, uma peça por degrau',
    caminho: 'coleção · progressivo · estética · sem pessoa · três produtos',
    mode: 'collection', mech: 'progressivo', argumento: 'estetica',
    alvo: 'Coleção de couro caramelo', categoria: 'bolsas, calçados e acessórios',
    itens: ['bolsa de ombro de couro caramelo', 'sandália de tiras de couro caramelo', 'cinto de couro caramelo'],
    publico: 'Mulher de 25 a 45 anos que compra bolsa, sandália e cinto da mesma coleção.',
    oferta: '1 ITEM 15% OFF · 2 ITENS 25% OFF · 3 ITENS 35% OFF',
    people: 'sem-pessoa', slots: 3,
    receita: [
      'O que define esta direção: uma escada real vira a escada do desconto. Cada degrau segura um produto e o seu percentual, subindo.',
      'Escada externa de pedra clara vista de lado em três quartos, luz de sol alta e parede clara ao fundo.',
      'Um produto inteiro em cada degrau, subindo da frente para trás.',
      'Na face vertical de cada degrau, em escuro: o percentual em caixa alta pesada, crescendo com o degrau. A marca pequena fica no alto.',
      'Esta peça não tem pessoa, headline, selo, cartão, preço ou CTA.',
      'Com mais degraus na oferta, a escada ganha degraus; com menos itens, um degrau pode ficar só com o percentual.',
    ],
  },

  /* ---------- produto único · até X% · função ---------- */
  {
    id: 'NOVA-29',
    nome: 'Mão com o produto e tópicos em linha fina',
    caminho: 'produto único · até X% · função · corpo sem rosto · duas cores',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Escova de dentes elétrica recarregável', categoria: 'higiene pessoal',
    variantes: ['branca', 'preta'],
    detalhes: 'cabo liso, um botão frontal, base de carregamento redonda',
    beneficios: ['Remove mais placa que a escova manual', 'Carga dura semanas', 'Timer de dois minutos'],
    publico: 'Adulto de 25 a 50 anos que quer trocar a escova manual pela elétrica.',
    oferta: 'ATÉ 50% DE DESCONTO',
    people: 'corpo-suporte', slots: 2, fillsWithVariants: true,
    receita: [
      'O que define esta direção: a mão mostra o produto de perto, a segunda cor fica em pé na base, e o argumento vem em três tópicos com ícone de linha fina.',
      'Fundo de banheiro claro, azulejo branco liso e desfocado.',
      'A mão, só até o pulso, segura uma unidade em pé. A outra cor fica em pé na base, ao lado e um pouco atrás.',
      'Do outro lado do quadro, empilhados e alinhados à esquerda: a marca pequena no alto; três tópicos curtos, cada um com um ícone de linha fina solto, sem círculo e sem fundo; e a oferta na base, com o número em corpo grande.',
      'Esta peça não tem selo, cartão, estrela de avaliação ou CTA.',
      'Com uma cor só, a unidade da base some e a mão fica sozinha.',
    ],
  },
  {
    id: 'NOVA-30',
    nome: 'Mão na bancada com as cores ao lado',
    caminho: 'produto único · até X% · função · corpo sem rosto · três cores',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Mini liquidificador portátil recarregável', categoria: 'eletroportáteis',
    variantes: ['branco', 'verde-menta', 'rosa-claro'],
    detalhes: 'copo transparente com tampa, base com um botão, carregamento USB',
    beneficios: ['Vitamina pronta em 30 segundos', 'Leva na bolsa', 'Carrega no USB'],
    publico: 'Adulto de 25 a 45 anos que prepara vitamina e shake em casa, sem tempo.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'corpo-suporte', slots: 3, fillsWithVariants: true,
    receita: [
      'O que define esta direção: uma mão ergue o produto cheio de vitamina numa cozinha real, e as outras cores estão em pé na bancada, na mesma luz. Uso e variedade na mesma foto.',
      'Cozinha clara, bancada de pedra clara e parede lisa clara ao fundo, com luz de janela.',
      'Só a mão e o antebraço aparecem, entrando pela borda com uma unidade cheia. As outras ficam em pé na bancada, ao lado, inteiras.',
      'Na parede livre, alinhados à esquerda: a marca pequena, uma headline de duas linhas com o benefício principal em caixa alta pesada e a oferta em uma linha.',
      'Esta peça não tem lista de tópicos, ícone, selo, cartão ou CTA.',
      'Com menos cores confirmadas, a bancada fica com menos unidades.',
    ],
  },
  {
    id: 'NOVA-31',
    nome: 'Produto ao centro com legendas apontando',
    caminho: 'produto único · até X% · função · sem pessoa · um produto',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Mochila antifurto para notebook', categoria: 'bolsas e mochilas',
    variantes: ['cinza-grafite'],
    detalhes: 'zíper escondido nas costas, entrada USB lateral, tecido impermeável liso',
    beneficios: ['Zíper escondido', 'Entrada USB', 'Tecido impermeável'],
    publico: 'Adulto de 20 a 40 anos que anda de transporte público com notebook.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'sem-pessoa', slots: 1,
    receita: [
      'O que define esta direção: o produto no centro e três legendas curtas ligadas por linhas finas às partes que elas descrevem. A peça explica o produto apontando para ele.',
      'Fundo cinza muito claro, liso e contínuo.',
      'O produto aparece em três quartos, no centro, inteiro, com sombra de contato curta.',
      'Três legendas de duas ou três palavras, em escuro, ligadas por linhas finas e retas às partes certas do produto. As linhas não cruzam o produto.',
      'No alto, centralizada, a marca pequena. Embaixo, centralizada, a oferta em uma linha de caixa alta pesada.',
      'Esta peça não tem pessoa, selo, cartão, ícone ou CTA.',
    ],
  },

  /* ---------- produto único · compre X leve Y · função ---------- */
  {
    id: 'NOVA-32',
    nome: 'Duas unidades com a conta desenhada',
    caminho: 'produto único · compre X leve Y · função · sem pessoa · duas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Lanterna tática recarregável', categoria: 'utilidades',
    variantes: ['preta'],
    detalhes: 'corpo de alumínio, lente frontal, botão traseiro',
    beneficios: ['Carrega no USB', 'Resiste à água', 'Alcance de 500 metros'],
    publico: 'Adulto de 25 a 55 anos que quer luz de emergência em casa.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'sem-pessoa', slots: 2, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: duas unidades idênticas em pé lado a lado, com “1 + 1” entre elas e uma linha de benefício embaixo.',
      'Fundo cinza muito claro, liso e contínuo.',
      'As duas unidades ficam em pé, no mesmo tamanho, com folga no meio. Entre elas, “1 + 1” em caixa alta pesada escura.',
      'No alto, centralizadas: a marca pequena e a oferta em uma linha de caixa alta pesada.',
      'Embaixo, uma única linha pequena e espaçada com os três benefícios separados por pontos.',
      'Esta peça não tem pessoa, ícone, embalagem, selo ou CTA.',
    ],
  },
  {
    id: 'NOVA-33',
    nome: 'Os dois joelhos, uma unidade em cada',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · duas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Joelheira de compressão', categoria: 'saúde e bem-estar',
    variantes: ['preta'],
    detalhes: 'malha de compressão lisa, abertura na patela, sem logo',
    beneficios: ['Alivia a dor ao caminhar', 'Estabiliza o joelho', 'Não escorrega'],
    publico: 'Adulto de 35 a 60 anos que sente dor no joelho ao caminhar ou subir escada.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'corpo-suporte', slots: 2, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: o produto vem em par porque o corpo tem dois joelhos. As duas pernas aparecem lado a lado, cada joelho com uma unidade.',
      'Fundo de estúdio claro e liso.',
      'As pernas aparecem de frente, lado a lado, enquadradas do meio da coxa até o meio da canela. A bermuda é lisa, neutra e escura.',
      'Numa faixa lateral, alinhados à esquerda: a marca pequena, os três benefícios em linhas curtas separadas por filetes finos e a oferta na base, em caixa alta pesada.',
      'Esta peça não tem selo, cartão, ícone, estrela de avaliação ou CTA.',
    ],
  },
  {
    id: 'NOVA-34',
    nome: 'Mão afundando um dos dois travesseiros',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · duas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Travesseiro ortopédico de espuma', categoria: 'casa',
    variantes: ['branco'],
    detalhes: 'formato anatômico com curva para o pescoço, capa lisa branca',
    beneficios: ['Alinha o pescoço durante o sono'],
    publico: 'Adulto de 30 a 55 anos que acorda com dor no pescoço.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'corpo-suporte', slots: 2, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: as duas unidades lado a lado na cama, e uma mão afunda uma delas mostrando a espuma que volta ao formato. O par é a oferta; o gesto é o argumento.',
      'Cama arrumada com lençol cinza-claro liso, vista de cima em diagonal, com luz de manhã vinda de janela lateral.',
      'Só a mão e o pulso aparecem, entrando pela borda e pressionando o centro de uma unidade. A outra fica intacta ao lado.',
      'Na área livre do lençol, no alto: a marca pequena, uma headline de uma linha com o benefício e a oferta em caixa alta pesada.',
      'Esta peça não tem lista de tópicos, ícone, selo, cartão ou CTA.',
    ],
  },
  {
    id: 'NOVA-35',
    nome: 'Perna com o produto e faixa escura de oferta',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · um produto',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Meia de compressão até o joelho', categoria: 'saúde e bem-estar',
    variantes: ['nude'],
    detalhes: 'compressão graduada, cano até abaixo do joelho, malha lisa',
    beneficios: ['Reduz o inchaço', 'Alivia o cansaço', 'Uso o dia todo'],
    publico: 'Mulher de 30 a 60 anos que passa o dia em pé e sente as pernas cansadas.',
    oferta: 'LEVE 3, PAGUE 2',
    people: 'corpo-suporte', slots: 1,
    receita: [
      'O que define esta direção: uma perna em perfil mostra o produto em uso, e uma faixa escura embaixo junta a oferta e os benefícios.',
      'Fundo cinza-claro quente, liso e contínuo.',
      'A perna aparece em perfil, do joelho até o pé descalço, apoiada na ponta.',
      'Na base, uma faixa sólida escura de ponta a ponta: a oferta em caixa alta pesada e clara de um lado, e os três benefícios empilhados do outro.',
      'A marca pequena fica no alto, alinhada à esquerda.',
      'Esta peça não tem selo, cartão, ícone ou CTA.',
    ],
  },
  {
    id: 'NOVA-36',
    nome: 'Produto em uso visto de costas',
    caminho: 'produto único · compre X leve Y · função · corpo sem rosto · um produto',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Fone de condução óssea', categoria: 'eletrônicos',
    variantes: ['preto'],
    detalhes: 'arco de titânio que passa atrás da nuca, apoio sobre a maçã do rosto, sem cabo',
    beneficios: ['Ouve música e o ambiente ao mesmo tempo'],
    publico: 'Homem de 20 a 45 anos que corre ao ar livre.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'corpo-suporte', slots: 1,
    receita: [
      'O que define esta direção: o produto em uso visto de costas, durante uma corrida real, com uma headline de benefício sobre o céu claro.',
      'Parque aberto com céu claro e liso ocupando a parte de cima do quadro; o resto do fundo levemente desfocado.',
      'A pessoa é vista de costas e de perto: nuca, orelhas e ombros, com o arco do fone passando atrás da nuca. Camiseta lisa em tom neutro.',
      'Sobre o céu, alinhados à esquerda: a marca pequena, uma headline de duas linhas com o benefício em caixa alta pesada escura e a oferta em uma linha abaixo.',
      'Esta peça não tem lista de tópicos, ícone, selo, cartão ou CTA.',
    ],
  },
];
