/*
 * Série 4 — consumível e cosmético.
 *
 * O banco inteiro foi construído em cima de produto durável: a peça mostra o objeto,
 * e acabou. Consumível tem uma lógica que nenhuma das 69 referências usa — o conteúdo
 * sai da embalagem, a linha inteira se alinha por altura, o ingrediente aparece cru
 * ao lado, o refil prova a economia, a dose é contada, a rotina é numerada.
 *
 * É isso que estas direções atacam. Cada uma parte de um recurso que só existe quando
 * o produto acaba e é recomprado, e nenhuma delas funcionaria com uma camiseta.
 */
export const serie4 = [
  /* ---------- o conteúdo sai da embalagem ---------- */
  {
    id: 'NOVA-45',
    nome: 'Textura do conteúdo ao lado do frasco fechado',
    caminho: 'produto único · até X% · estética · sem pessoa · um produto',
    mode: 'single', mech: 'percentual', argumento: 'estetica',
    alvo: 'Creme hidratante facial em pote', categoria: 'cosméticos',
    variantes: ['pote de vidro fosco branco'],
    detalhes: 'pote baixo de vidro fosco com tampa metálica, sem rótulo de marca, creme branco denso',
    publico: 'Mulher de 25 a 45 anos que compra cosmético pela textura e pelo acabamento.',
    oferta: 'ATÉ 50% DE DESCONTO',
    people: 'sem-pessoa', slots: 1,
    receita: [
      'O que define esta direção: o produto fechado de um lado e o conteúdo dele espalhado direto na superfície do outro. A textura do creme é tão importante quanto a embalagem — é ela que o cliente compra.',
      'Superfície de pedra clara e fosca, contínua, ocupando o quadro inteiro, com luz suave vinda de cima e sombra curta.',
      'O pote aparece fechado, em três quartos, ligeiramente fora do centro, inteiro e nítido.',
      'Ao lado dele, sobre a mesma pedra, uma porção generosa do conteúdo espalhada com relevo real: picos, ondas e brilho de superfície úmida, num traço solto e assimétrico que não vira coração nem forma desenhada.',
      'A textura recebe a mesma luz do produto e fica igualmente nítida. As duas coisas juntas ocupam a maior parte do quadro.',
      'No alto, alinhados à esquerda: a marca pequena e a oferta em duas linhas de caixa alta pesada e escura.',
      'Nenhuma cor gráfica: toda a cor vem do produto e do conteúdo.',
      'Esta peça não tem pessoa, mão, espátula, ingrediente, cenário, selo, moldura ou CTA.',
    ],
  },
  {
    id: 'NOVA-46',
    nome: 'Macro do conteúdo com o frasco pequeno em cima',
    caminho: 'produto único · até X% · estética · sem pessoa · um produto · peça sem texto',
    mode: 'single', mech: 'percentual', argumento: 'estetica',
    alvo: 'Sérum facial com conta-gotas', categoria: 'cosméticos',
    variantes: ['frasco âmbar'],
    detalhes: 'frasco de vidro âmbar com conta-gotas preto, sem rótulo de marca, sérum transparente',
    publico: 'Mulher de 25 a 45 anos que compra sérum pela concentração e pelo acabamento.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'sem-pessoa', slots: 1, silent: true,
    receita: [
      'O que define esta direção: o quadro inteiro é o conteúdo em macro absoluto, e o frasco aparece pequeno, pousado sobre ele. A escala inverte: o líquido é o cenário e a embalagem é o objeto.',
      'Uma poça larga e rasa do próprio sérum cobre o quadro de borda a borda, com bolhas, viscosidade e reflexo de luz visíveis em detalhe.',
      'O frasco fica pousado sobre a poça, pequeno em relação a ela, inteiro, nítido e em pé, com o reflexo dele deitado no líquido.',
      'Luz lateral rasante cria brilho alto nas bordas das bolhas e escurece o fundo da poça, dando profundidade.',
      'Esta peça não tem texto, marca, pessoa, mão, ingrediente, cenário, selo, moldura ou efeito gráfico.',
    ],
  },

  /* ---------- a linha inteira ---------- */
  {
    id: 'NOVA-47',
    nome: 'Linha completa alinhada pela base, subindo em altura',
    caminho: 'coleção · progressivo · estética · sem pessoa · quatro produtos',
    mode: 'collection', mech: 'progressivo', argumento: 'estetica',
    alvo: 'Linha de tratamento capilar', categoria: 'cosméticos',
    itens: ['shampoo em frasco alto', 'condicionador em frasco alto', 'máscara de tratamento em pote', 'óleo finalizador em frasco pequeno com conta-gotas'],
    publico: 'Mulher de 25 a 50 anos que monta a rotina capilar completa.',
    oferta: '2 ITENS 15% OFF · 3 ITENS 25% OFF · 4 ITENS 35% OFF',
    people: 'sem-pessoa', slots: 4,
    receita: [
      'O que define esta direção: os frascos da linha ficam lado a lado, todos apoiados na mesma base, e as alturas diferentes desenham uma escada natural. A escada do desconto é a própria linha de produtos, e os percentuais correm rentes a essa silhueta.',
      'Fundo claro e quente, liso e contínuo, com luz suave de cima e sombras curtas alinhadas na mesma direção.',
      'Os produtos ficam em fila, encostando quase, ordenados do mais baixo ao mais alto, todos de frente e no mesmo plano. Nenhum é girado nem adiantado.',
      'Acompanhando a linha do topo dos frascos, subindo com ela: a quantidade em corpo pequeno e o percentual em caixa alta pesada logo abaixo, um par por degrau. O último percentual é o maior.',
      'A marca pequena fica no alto, alinhada à esquerda, longe dos percentuais.',
      'Toda a cor vem dos frascos e do conteúdo; o texto é escuro e sem cor de acento.',
      'Esta peça não tem pessoa, mão, ingrediente, caixa, selo, moldura ou CTA.',
      'Com menos itens confirmados, a fila encurta e sobra mais fundo; nenhum frasco é inventado para completar a escada.',
    ],
  },
  {
    id: 'NOVA-48',
    nome: 'Kit na caixa aberta com berço recortado',
    caminho: 'coleção · até X% · estética · sem pessoa · três produtos',
    mode: 'collection', mech: 'percentual', argumento: 'estetica',
    alvo: 'Kit de cuidados masculinos', categoria: 'cosméticos',
    itens: ['shampoo para barba em frasco', 'balm para barba em pote', 'óleo para barba em frasco com conta-gotas'],
    publico: 'Homem de 25 a 45 anos que compra kit de cuidados como presente ou reposição.',
    oferta: 'ATÉ 40% DE DESCONTO',
    people: 'sem-pessoa', slots: 3,
    receita: [
      'O que define esta direção: uma caixa rígida aberta, vista de cima, com um berço interno recortado sob medida, e cada produto encaixado no seu vão. É o kit como objeto fechado, não como produtos soltos lado a lado.',
      'A caixa ocupa quase todo o quadro, apoiada sobre superfície escura e fosca, com a tampa encostada atrás, inclinada, mostrando o interior liso.',
      'O berço interno é de espuma ou papelão em tom neutro, com vãos do formato exato de cada frasco. Cada produto fica deitado no seu vão, inteiro, visível e sem sobrepor o vizinho.',
      'Luz difusa de cima, sem reflexo duro no vidro e sem sombra cortando os produtos.',
      'Na superfície escura ao lado da caixa, alinhados à esquerda: a marca pequena e a oferta em duas linhas de caixa alta pesada e clara.',
      'Esta peça não tem pessoa, mão, laço, papel de presente, ingrediente, selo, moldura ou CTA.',
      'Com menos itens confirmados, o berço tem menos vãos e a caixa fica mais estreita; nenhum vão fica vazio.',
    ],
  },

  /* ---------- o que tem dentro ---------- */
  {
    id: 'NOVA-49',
    nome: 'Ingrediente cru cortado ao lado do produto',
    caminho: 'produto único · até X% · função · sem pessoa · um produto',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Protetor solar facial em bisnaga', categoria: 'cosméticos',
    variantes: ['bisnaga branca'],
    detalhes: 'bisnaga branca fosca com tampa de rosca, sem rótulo de marca, textura fluida',
    beneficios: ['Proteção alta para o rosto', 'Não deixa o rosto branco', 'Resiste à água'],
    publico: 'Adulto de 25 a 50 anos que usa protetor solar no rosto todo dia.',
    oferta: 'ATÉ 50% DE DESCONTO',
    people: 'sem-pessoa', slots: 1,
    receita: [
      'O que define esta direção: o produto ao lado do ingrediente cru que ele carrega, cortado e fresco. O ingrediente prova a promessa sem que nenhum texto precise explicá-la.',
      'Superfície de pedra clara e molhada, com gotas de água reais espalhadas, sob luz de sol direta e sombra marcada.',
      'O produto fica em pé no centro, inteiro e nítido, com gotas de água na própria embalagem.',
      'Ao lado, o ingrediente cru aparece inteiro e cortado ao meio, mostrando o interior, na mesma luz e na mesma nitidez do produto — mas menor que ele.',
      'Numa faixa do fundo livre, alinhados à esquerda: a marca pequena, os benefícios em linhas curtas separadas por filetes finos, e a oferta na base com o número em corpo grande.',
      'Todo o texto é escuro sobre o fundo claro; a peça não tem cor de acento, tarja nem selo.',
      'Esta peça não tem pessoa, mão, ícone, cartão, moldura ou CTA.',
    ],
  },
  {
    id: 'NOVA-50',
    nome: 'Frasco cortado ao meio mostrando as camadas',
    caminho: 'produto único · até X% · função · sem pessoa · um produto',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Desodorante em bastão', categoria: 'higiene pessoal',
    variantes: ['bastão branco'],
    detalhes: 'bastão cilíndrico branco com base giratória, sem rótulo de marca, massa sólida branca',
    beneficios: ['72 horas de proteção', 'Não mancha a roupa', 'Sem álcool'],
    publico: 'Adulto de 20 a 45 anos que quer desodorante que dure o dia inteiro.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'sem-pessoa', slots: 1,
    receita: [
      'O que define esta direção: duas unidades do mesmo produto lado a lado — uma inteira e fechada, outra aberta em corte reto mostrando o interior. O corte é o argumento: o cliente vê o que está comprando por dentro.',
      'Fundo cinza muito claro, liso e contínuo, com luz difusa e sombra de contato curta sob cada unidade.',
      'As duas unidades ficam em pé, lado a lado, no mesmo tamanho e no mesmo ângulo. A da direita está seccionada verticalmente, com o corte limpo e reto, revelando a massa interna e o mecanismo.',
      'A face cortada é nítida e bem iluminada, sem brilho plástico e sem aparência de desenho técnico.',
      'Três legendas curtas em escuro, ligadas por linhas finas retas às partes do corte que elas descrevem. As linhas não cruzam o produto.',
      'No alto, centralizada, a marca pequena. Embaixo, centralizada, a oferta em uma linha de caixa alta pesada.',
      'Esta peça não tem pessoa, mão, ícone, cartão, selo ou CTA.',
    ],
  },

  /* ---------- consumível é recompra ---------- */
  {
    id: 'NOVA-51',
    nome: 'Produto ao lado do refil, com a conta desenhada',
    caminho: 'produto único · compre X leve Y · função · sem pessoa · duas unidades',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Sabonete líquido corporal', categoria: 'higiene pessoal',
    variantes: ['frasco com válvula'],
    detalhes: 'frasco de plástico fosco com válvula pump e refil em sachê de pé, ambos sem rótulo de marca',
    beneficios: ['Um refil enche o frasco duas vezes', 'Espuma densa', 'Não resseca'],
    publico: 'Adulto de 25 a 55 anos que repõe sabonete líquido em casa.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'sem-pessoa', slots: 2,
    receita: [
      'O que define esta direção: o frasco com válvula de um lado e o refil de pé do outro, com uma seta larga entre eles apontando do refil para o frasco. A peça mostra a recompra em vez de anunciá-la só no texto.',
      'Fundo claro e liso, contínuo, com luz difusa e sombra de contato curta sob cada peça.',
      'As duas peças ficam em pé, no mesmo plano, com folga entre elas. O frasco é ligeiramente maior e fica à frente; o refil fica um passo atrás.',
      'Entre os dois, uma seta larga e cheia, escura, apontando do refil para o frasco. A seta é menor que qualquer uma das peças.',
      'No alto, centralizados: a marca pequena e a oferta em uma linha de caixa alta pesada. Embaixo, uma única linha pequena e espaçada com os benefícios separados por pontos.',
      'A seta é o único elemento gráfico da peça, e é da mesma cor do texto.',
      'Esta peça não tem pessoa, mão, ícone, cartão, selo, moldura ou CTA.',
    ],
  },
  {
    id: 'NOVA-52',
    nome: 'Dose diária contada ao lado do pote',
    caminho: 'produto único · compre X leve Y · função · sem pessoa · um produto',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Suplemento em cápsulas', categoria: 'suplementos',
    variantes: ['pote branco'],
    detalhes: 'pote plástico branco fosco com tampa de rosca, sem rótulo de marca, cápsulas brancas e douradas',
    beneficios: ['Duas cápsulas por dia', 'Pote com 60 doses', 'Sem sabor residual'],
    publico: 'Adulto de 30 a 55 anos que toma suplemento diário.',
    oferta: 'COMPRE 2, LEVE 3',
    people: 'sem-pessoa', slots: 1, repeatsSameProduct: true,
    receita: [
      'O que define esta direção: o pote fechado e, ao lado, as cápsulas contadas e alinhadas em fileira certinha sobre a superfície. Dá para contar a dose com o olho — esse é o argumento.',
      'Superfície de pedra clara e fosca vista de cima, contínua, com luz suave e sombras curtas.',
      'O pote aparece deitado ou em pé num canto, inteiro e nítido.',
      'As cápsulas ficam alinhadas em fileira regular, todas na mesma direção e com espaçamento igual, saindo da boca do pote em direção ao lado oposto do quadro. A quantidade da fileira é a dose que o benefício declara.',
      'Na área livre, alinhados à esquerda: a marca pequena, os benefícios em linhas curtas separadas por filetes finos, e a oferta na base em caixa alta pesada.',
      'Todo o texto é escuro; a peça não tem tarja, selo nem cor de acento. A cor vem só do produto.',
      'Esta peça não tem pessoa, mão, copo, água, ícone, cartão ou CTA.',
    ],
  },

  /* ---------- perfumaria ---------- */
  {
    id: 'NOVA-53',
    nome: 'Frasco em luz âmbar com o respingo congelado',
    caminho: 'produto único · até X% · estética · sem pessoa · um produto',
    mode: 'single', mech: 'percentual', argumento: 'estetica',
    alvo: 'Perfume em frasco de vidro facetado', categoria: 'perfumaria',
    variantes: ['vidro facetado com líquido âmbar'],
    detalhes: 'frasco pesado de vidro facetado com tampa maciça, sem rótulo de marca, líquido âmbar',
    publico: 'Adulto de 25 a 50 anos que compra perfume pela apresentação e pelo frasco.',
    oferta: 'ATÉ 40% DE DESCONTO',
    people: 'sem-pessoa', slots: 1,
    receita: [
      'O que define esta direção: o frasco em pé sobre uma lâmina de líquido, com um respingo congelado subindo ao lado dele. O movimento parado é o que dá o clima, e a peça é quase toda escura.',
      'Fundo escuro profundo, quase preto, com uma única luz âmbar quente vindo de trás e de baixo, atravessando o vidro e acendendo o líquido por dentro.',
      'A base é uma lâmina rasa do mesmo líquido, espelhando o frasco, com o reflexo alongado descendo no quadro.',
      'Ao lado do frasco, um respingo congelado sobe em coroa, com gotas soltas no ar, todas nítidas e sem borrão.',
      'O frasco é o ponto mais brilhante da imagem; os cantos do quadro escurecem por completo.',
      'Na área escura do alto, alinhados à esquerda: a marca pequena e clara e a oferta em duas linhas de caixa alta pesada e clara.',
      'Só existem três cores: o escuro do fundo, o âmbar do líquido e o claro do texto.',
      'Esta peça não tem pessoa, mão, flor, especiaria, caixa, selo, moldura ou CTA.',
    ],
  },

  /* ---------- rotina ---------- */
  {
    id: 'NOVA-54',
    nome: 'Rotina numerada com um produto por passo',
    caminho: 'coleção · até X% · estética · corpo sem rosto · três produtos',
    mode: 'collection', mech: 'percentual', argumento: 'estetica',
    alvo: 'Rotina facial de três passos', categoria: 'cosméticos',
    itens: ['gel de limpeza em bisnaga', 'tônico em frasco alto', 'hidratante em pote'],
    publico: 'Mulher de 20 a 40 anos que está montando a primeira rotina de pele.',
    oferta: 'ATÉ 45% DE DESCONTO',
    people: 'corpo-suporte', slots: 3,
    receita: [
      'O que define esta direção: o quadro se divide em três faixas verticais iguais, uma por passo da rotina, e cada faixa tem o seu número grande, o seu produto e a mão aplicando o conteúdo. A ordem de uso é a composição.',
      'As três faixas repetem o mesmo fundo claro e liso, a mesma luz e o mesmo enquadramento, separadas por respiros finos.',
      'Em cada faixa, uma mão aparece só até o pulso, com uma porção do conteúdo daquele passo sobre as pontas dos dedos ou no dorso. Nenhuma outra parte do corpo entra no quadro.',
      'O produto de cada passo fica em pé atrás da mão, inteiro e nítido, e é maior que a mão na leitura.',
      'No alto de cada faixa, um número grande e escuro — 1, 2 e 3 — e abaixo dele uma palavra só dizendo o passo.',
      'Na base, atravessando as três faixas, uma linha com a marca pequena de um lado e a oferta em caixa alta pesada do outro.',
      'Todo o texto é escuro; a peça não tem tarja, selo nem cor de acento.',
      'Esta peça não tem rosto, cartão, ícone, moldura ou CTA.',
      'Com menos itens confirmados, a peça tem menos faixas e cada uma fica mais larga; a numeração acompanha.',
    ],
  },
];
