/*
 * Primeira leva de criativos nativos.
 *
 * Nativo não é família visual: é outro regime. A peça funciona porque não parece
 * anúncio, então a regra da casa sai e entra a regra do nativo. Todas aqui são
 * `native: true` e `drivers: ['funcao']` — nativo vive onde existe um problema para
 * resolver, e é por isso que o print do Pedro é quase todo saúde, dor, pet e casa.
 *
 * A receita aqui descreve uma FOTO QUE ALGUÉM TIROU, não uma composição. Por isso
 * ela não fala de bloco de texto, alinhamento, hierarquia nem oferta: nada disso
 * existe na imagem. O que ela precisa dizer é o que está na cena, de que ângulo, com
 * que luz e o que revela o problema ou a mudança.
 *
 * Os dez arquétipos vieram da leitura do print: produto na casa real, parte do corpo
 * com o problema, pessoa comum sem pose, pet, comida e ingrediente, cena sem produto,
 * papel escrito à mão, objeto em uso, antes e depois caseiro, e detalhe que denuncia
 * o problema.
 */
export const nativos = [
  {
    id: 'NAT-01',
    nome: 'Produto esquecido na bancada da cozinha',
    caminho: 'nativo · produto único · até X% · função · produto na casa real',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Suplemento de magnésio em cápsulas', categoria: 'suplementos',
    variantes: ['pote branco'],
    detalhes: 'pote plástico branco com tampa de rosca, sem rótulo de marca',
    beneficios: ['Ajuda a relaxar à noite', 'Duas cápsulas por dia'],
    publico: 'Adulto de 40 a 65 anos que dorme mal e acorda cansado.',
    oferta: 'ATÉ 50% DE DESCONTO',
    people: 'sem-pessoa',
    receita: [
      'O que define esta direção: a foto que alguém tira da própria bancada de manhã, sem arrumar nada. O produto está ali no meio da rotina, não em cima de um pedestal.',
      'Bancada de cozinha comum, com a pia parcialmente visível, um pano dobrado torto, um copo usado e a luz cinzenta da manhã entrando pela janela.',
      'O produto fica em pé perto da borda, ligeiramente fora do centro, com a tampa apoiada ao lado como se tivesse acabado de ser aberto.',
      'A câmera está na altura do peito de quem está em pé, apontada um pouco para baixo, com a bancada saindo pela borda inferior.',
      'A foto tem o desfoque leve de quem fotografou de perto sem firmar a mão, e a cor puxa para o frio da luz natural.',
      'Nada na cena foi arrumado para a foto: se um objeto está fora do lugar, ele fica.',
    ],
  },
  {
    id: 'NAT-02',
    nome: 'Pé descalço no chão, no primeiro passo do dia',
    caminho: 'nativo · produto único · até X% · função · parte do corpo com o problema',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Palmilha ortopédica de gel', categoria: 'saúde e bem-estar',
    variantes: ['gel translúcido'],
    detalhes: 'palmilha de gel transparente com base cinza, sem marca aparente',
    beneficios: ['Alivia a dor no calcanhar', 'Cabe em qualquer sapato'],
    publico: 'Adulto de 40 a 65 anos que sente dor no calcanhar ao levantar da cama.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'corpo-suporte',
    receita: [
      'O que define esta direção: a foto que alguém tira do próprio pé, olhando de cima, no momento em que dói. É o gesto de quem quer mostrar o problema para outra pessoa.',
      'Quarto comum de manhã, chão de piso frio, o pé da cama e um pedaço de lençol entrando na borda do quadro.',
      'A câmera é o próprio olhar de quem está sentado na beira da cama: aponta para baixo, em ângulo inclinado, e mostra o pé apoiado no chão.',
      'O produto aparece pequeno, dentro de um sapato caído de lado ao alcance da mão, parcialmente na sombra.',
      'A luz é fraca e desigual, com o contraste alto de manhã cedo. Sombra funda sob a cama.',
      'Nada de close de estúdio, pele retocada, unha feita ou pedicure. É um pé comum de uma pessoa comum.',
    ],
  },
  {
    id: 'NAT-03',
    nome: 'Cachorro deitado no tapete, visto de cima',
    caminho: 'nativo · produto único · compre X leve Y · função · pet',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Petisco dental para cães', categoria: 'pet',
    variantes: ['sachê'],
    detalhes: 'sachê plástico fosco sem marca aparente, petiscos alongados em formato de escova',
    beneficios: ['Reduz o mau hálito', 'Um por dia'],
    publico: 'Adulto de 30 a 60 anos que tem cachorro em casa e sente o hálito dele.',
    oferta: 'COMPRE 2, LEVE 3',
    people: 'sem-pessoa',
    receita: [
      'O que define esta direção: a foto que o dono tira do próprio cachorro deitado, do jeito que ele está, com o produto largado ao lado. É a foto que uma pessoa manda para a amiga.',
      'Sala comum, tapete um pouco puído, sofá cortado na borda do quadro, brinquedo do cachorro esquecido no canto.',
      'O cachorro está deitado de lado, relaxado, com a cabeça apoiada no tapete e os olhos semicerrados. Ele ocupa a maior parte do quadro.',
      'O sachê do produto está aberto e caído ao lado dele, com alguns petiscos fora, sem nenhum arranjo.',
      'A câmera aponta para baixo da altura de quem está em pé, levemente torta, e a foto tem grão de luz baixa de fim de tarde.',
      'Nada de cachorro de banco de imagem, pelo escovado, coleira nova ou cenário limpo.',
    ],
  },
  {
    id: 'NAT-04',
    nome: 'Duas fotos do mesmo canto da casa, com meses de diferença',
    caminho: 'nativo · produto único · até X% · função · antes e depois caseiro',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Desumidificador elétrico de ambiente', categoria: 'casa',
    variantes: ['branco'],
    detalhes: 'aparelho branco compacto com grade frontal e reservatório transparente, sem marca aparente',
    beneficios: ['Tira o mofo do ar', 'Esvazia sozinho no reservatório'],
    publico: 'Adulto de 30 a 60 anos que tem mofo na parede do quarto ou do armário.',
    oferta: 'ATÉ 55% DE DESCONTO',
    people: 'sem-pessoa',
    receita: [
      'O que define esta direção: duas fotos caseiras do mesmo canto de parede, tiradas do mesmo lugar em momentos diferentes, encostadas uma na outra. Não existe cartão, borda, rótulo nem seta: são só duas fotos lado a lado, como quem junta duas imagens no celular.',
      'O canto é o encontro de duas paredes atrás de um móvel, num quarto comum, com rodapé e um pedaço do móvel aparecendo.',
      'Na primeira, a parede tem manchas escuras de mofo e a tinta descascando na quina. Na segunda, o mesmo canto está limpo e o produto aparece no chão, encostado na parede, ligado.',
      'As duas fotos têm o mesmo enquadramento torto e a mesma luz de lâmpada amarelada, porque foram tiradas pela mesma pessoa no mesmo lugar.',
      'A emenda entre as duas é uma linha simples, sem moldura e sem espaço branco.',
      'Nada de texto, etiqueta, rótulo de antes e depois, seta ou marcação de cor.',
    ],
  },
  {
    id: 'NAT-05',
    nome: 'Bilhete escrito à mão sobre a mesa',
    caminho: 'nativo · produto único · até X% · função · papel escrito à mão',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Organizador de comprimidos semanal', categoria: 'saúde e bem-estar',
    variantes: ['plástico branco'],
    detalhes: 'caixa plástica branca com sete compartimentos e tampas identificadas por dia',
    beneficios: ['Não esquece a dose', 'Uma semana inteira de uma vez'],
    publico: 'Adulto de 55 a 75 anos que toma remédio todo dia e esquece a dose.',
    oferta: 'ATÉ 45% DE DESCONTO',
    people: 'sem-pessoa',
    receita: [
      'O que define esta direção: um bilhete escrito à mão numa folha comum, fotografado de cima sobre a mesa, com o produto encostado ao lado. A letra é de alguém de verdade, não uma fonte imitando escrita.',
      'Mesa de madeira gasta de cozinha, com a caneta largada em cima do papel e um pedaço de toalha de mesa na borda.',
      'O papel é uma folha de bloco comum, levemente amassada, escrita a caneta esferográfica azul, com letra de pessoa mais velha, linha irregular e uma palavra rasurada.',
      'O bilhete traz um lembrete curto e doméstico, escrito à mão, sem nada de publicitário.',
      'O produto fica ao lado do papel, aberto, com alguns compartimentos cheios e outros vazios.',
      'A câmera aponta direto para baixo, com leve inclinação, e a sombra do celular de quem fotografa aparece na borda.',
      'Nada de caligrafia bonita, papel novo, caneta-tinteiro ou mesa arrumada.',
    ],
  },
  {
    id: 'NAT-06',
    nome: 'Produto no porta-copos do carro, parado no trânsito',
    caminho: 'nativo · produto único · compre X leve Y · função · produto em uso real',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Garrafa térmica com tampa de rosca', categoria: 'utilidades',
    variantes: ['inox escovado'],
    detalhes: 'garrafa de aço inox escovado com tampa de rosca e base emborrachada, sem marca aparente',
    beneficios: ['Mantém quente por 12 horas', 'Cabe no porta-copos'],
    publico: 'Adulto de 25 a 55 anos que passa horas no carro e quer café quente.',
    oferta: 'COMPRE 1, LEVE 2',
    people: 'sem-pessoa',
    receita: [
      'O que define esta direção: a foto que alguém tira de dentro do próprio carro, parado, com o celular na mão. O produto está no porta-copos, usado, no meio da vida real.',
      'Interior de carro comum, console entre os bancos, câmbio e um pedaço do banco do passageiro. Pelo para-brisa, um trânsito parado e desfocado.',
      'O produto está encaixado no porta-copos, ligeiramente sujo de uso, com uma marca de dedo no inox.',
      'A câmera está na altura do banco, apontada para baixo em diagonal, enquadrando o console e parte do para-brisa.',
      'A luz é a do dia entrando pelo vidro, com reflexo no painel e uma faixa estourada onde o sol bate.',
      'Nada de carro de revista, painel limpo, produto novo sem marca de uso ou estrada bonita ao fundo.',
    ],
  },
  {
    id: 'NAT-07',
    nome: 'Pessoa comum sentada no sofá, foto tirada por outra pessoa',
    caminho: 'nativo · produto único · até X% · função · pessoa comum sem pose',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Almofada de apoio lombar', categoria: 'casa',
    variantes: ['cinza'],
    detalhes: 'almofada de espuma em formato anatômico com capa de tecido cinza e alça elástica, sem marca aparente',
    beneficios: ['Alivia a dor nas costas sentado', 'Prende na cadeira'],
    publico: 'Adulto de 40 a 65 anos que passa o dia sentado e sente dor lombar.',
    oferta: 'ATÉ 50% DE DESCONTO',
    people: 'humanizado',
    receita: [
      'O que define esta direção: a foto que um parente tira de alguém sentado, sem avisar. A pessoa não posa, não olha para a câmera e está no meio de outra coisa.',
      'Sala comum de casa, sofá com manta torta, mesinha com controle remoto e um copo, parede com quadro pequeno.',
      'A pessoa está sentada de lado, com o produto apoiado nas costas, olhando para a TV fora do quadro, com expressão neutra e roupa de estar em casa.',
      'A câmera está à altura de quem está em pé na sala, a alguns passos, e pega a pessoa inteira do joelho para cima, com o sofá cortado pela borda.',
      'A luz é de lâmpada de teto misturada com o resto de luz da janela, com cor desigual e sombra dura embaixo.',
      'Nada de modelo, maquiagem, roupa nova, sorriso para a câmera ou sala de decoração.',
    ],
  },
  {
    id: 'NAT-08',
    nome: 'Detalhe do problema num objeto de casa',
    caminho: 'nativo · produto único · até X% · função · detalhe que denuncia o problema',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Removedor de bolinhas de tecido elétrico', categoria: 'casa',
    variantes: ['branco'],
    detalhes: 'aparelho cilíndrico branco com cabeça de lâmina circular e reservatório removível, sem marca aparente',
    beneficios: ['Tira as bolinhas sem estragar o tecido', 'Funciona com pilha'],
    publico: 'Adulto de 30 a 60 anos que tem roupa boa cheia de bolinha.',
    oferta: 'ATÉ 55% DE DESCONTO',
    people: 'corpo-suporte',
    receita: [
      'O que define esta direção: um close de celular no problema, feito por quem estava incomodado com ele. A mão puxa o tecido para mostrar melhor, e o produto está por perto sem protagonismo.',
      'Um casaco escuro estendido na cama, com o lençol amassado aparecendo ao redor.',
      'A mão de uma pessoa segura e estica um pedaço do tecido, deixando as bolinhas claras visíveis contra o escuro. Só a mão e parte do pulso aparecem.',
      'O produto está largado sobre a cama ao lado, um pouco fora de foco, com o reservatório cheio de fiapos.',
      'A câmera está muito perto, com foco curto: parte do tecido está nítida e o resto desmancha.',
      'A luz é de lâmpada do quarto, amarelada, com a sombra da mão caindo sobre o tecido.',
      'Nada de estúdio, fundo neutro, tecido novo ou iluminação montada.',
    ],
  },
  {
    id: 'NAT-09',
    nome: 'Ingrediente e produto na mesa do café da manhã',
    caminho: 'nativo · produto único · compre X leve Y · função · comida e ingrediente',
    mode: 'single', mech: 'leve-mais', argumento: 'funcao',
    alvo: 'Colágeno em pó sem sabor', categoria: 'suplementos',
    variantes: ['pote branco'],
    detalhes: 'pote plástico branco com tampa larga e colher dosadora dentro, sem marca aparente',
    beneficios: ['Sem sabor, dissolve no café', 'Uma colher por dia'],
    publico: 'Mulher de 35 a 60 anos que toma colágeno de manhã.',
    oferta: 'COMPRE 2, LEVE 3',
    people: 'sem-pessoa',
    receita: [
      'O que define esta direção: a foto de uma mesa de café da manhã de verdade, no meio do preparo, com o produto entre as outras coisas. A cena está pela metade, não montada.',
      'Mesa comum com uma caneca de café pela metade, uma colher suja apoiada no guardanapo, migalhas e um celular virado para baixo.',
      'O produto está aberto ao lado da caneca, com a colher dosadora dentro e um pouco de pó derramado na mesa.',
      'A câmera aponta de cima, em ângulo torto, cortando a borda da mesa e pegando um pedaço da cadeira.',
      'A luz é a da manhã pela janela lateral, com reflexo na caneca e sombras compridas.',
      'Nada de flat lay arrumado, louça combinando, flores, tábua de madeira decorativa ou fundo neutro.',
    ],
  },
  {
    id: 'NAT-10',
    nome: 'Cena do lugar onde o problema acontece, sem produto',
    caminho: 'nativo · produto único · até X% · função · cena sem produto',
    mode: 'single', mech: 'percentual', argumento: 'funcao',
    alvo: 'Sensor de presença com luz para corredor', categoria: 'casa',
    variantes: ['branco'],
    detalhes: 'barra de luz branca com sensor de presença, fixação adesiva e carregamento USB, sem marca aparente',
    beneficios: ['Acende sozinho quando alguém passa', 'Instala sem fio'],
    publico: 'Adulto de 45 a 75 anos que levanta de madrugada e anda no escuro.',
    oferta: 'ATÉ 60% DE DESCONTO',
    people: 'sem-pessoa',
    receita: [
      'O que define esta direção: a foto do lugar onde o problema acontece, sem o produto nenhum no quadro. A cena sozinha faz a pessoa reconhecer a própria casa.',
      'Um corredor comum de casa à noite, quase todo escuro, com portas fechadas dos dois lados e o batente do quarto aparecendo perto.',
      'A única luz é um resto de claridade vindo de uma porta entreaberta no fim do corredor, desenhando uma faixa no chão.',
      'A câmera está à altura de quem acabou de levantar, apontada para o fundo do corredor, um pouco inclinada.',
      'A foto tem grão alto e é escura de verdade: os cantos somem, e só o piso perto da faixa de luz aparece.',
      'Esta peça não mostra o produto. Ela mostra o problema.',
      'Nada de luz bonita, casa de revista, corredor largo ou decoração.',
    ],
  },
];
